{- Free cocartesian category generated by a category.

   Everything here is obtained from the free cartesian category by
   duality: the free cocartesian category on C is the opposite of the
   free cartesian category on C ^op.  Since `Category` and `Functor`
   are no-eta records, `_^op` is not a strict involution, so the
   transport is arranged so that functors out of a free cocartesian
   category always have codomain of the shape `D ^op`.
-}
{-# OPTIONS --lossy-unification #-}
module Cubical.Categories.Instances.Free.CocartesianCategory.OnCategory
  where

open import Cubical.Foundations.Prelude

open import Cubical.Categories.Category.Base
open import Cubical.Categories.Functor
open import Cubical.Categories.NaturalTransformation
open import Cubical.Categories.Isomorphism
open import Cubical.Categories.Limits.Cartesian.Base
open import Cubical.Categories.Instances.Functors
open import Cubical.Categories.Limits.Terminal.More
open import Cubical.Categories.Limits.BinProduct.More
open import Cubical.Categories.Limits.Initial
open import Cubical.Categories.Bicategory.Instances.CAT.Structured.Terminal
open import Cubical.Categories.Bicategory.Instances.CAT.Structured.Cartesian

open import Cubical.Categories.Instances.Free.CartesianCategory.OnCategory

private
  variable
    ℓA ℓA' ℓB ℓB' ℓC ℓC' ℓD ℓD' ℓE ℓE' : Level

open Category
open Functor
open NatTrans
open NatIso
open isIso
open CartesianCategory renaming (C to Cat) using (term; bp)

-- Data swaps for `_^op`.  Each is definitionally transparent: only
-- the order of the arguments of `F-seq` changes.
module _ {A : Category ℓA ℓA'} {B : Category ℓB ℓB'} where
  op₂ : Functor A B → Functor (A ^op) (B ^op)
  op₂ F .F-ob = F .F-ob
  op₂ F .F-hom = F .F-hom
  op₂ F .F-id = F .F-id
  op₂ F .F-seq f g = F .F-seq g f

  unop₂ : Functor (A ^op) (B ^op) → Functor A B
  unop₂ F .F-ob = F .F-ob
  unop₂ F .F-hom = F .F-hom
  unop₂ F .F-id = F .F-id
  unop₂ F .F-seq f g = F .F-seq g f


module _ {A : Category ℓA ℓA'} {B : Category ℓB ℓB'}
  {P Q : Functor (A ^op) (B ^op)} where
  unopNT : NatTrans P Q → NatTrans (unop₂ Q) (unop₂ P)
  unopNT σ .N-ob = σ .N-ob
  unopNT σ .N-hom f = sym (σ .N-hom f)

  opNT : NatTrans (unop₂ Q) (unop₂ P) → NatTrans P Q
  opNT σ .N-ob = σ .N-ob
  opNT σ .N-hom f = sym (σ .N-hom f)

  unopNT-inj : {σ τ : NatTrans P Q} → unopNT σ ≡ unopNT τ → σ ≡ τ
  unopNT-inj p = makeNatTransPath (λ i x → p i .N-ob x)

  opNatIso : NatIso (unop₂ Q) (unop₂ P) → NatIso P Q
  opNatIso ı .trans = opNT (ı .trans)
  opNatIso ı .nIso A .inv = ı .nIso A .inv
  opNatIso ı .nIso A .sec = ı .nIso A .ret
  opNatIso ı .nIso A .ret = ı .nIso A .sec


module _ (C : Category ℓC ℓC') where
  private
    XC = |FreeCartesianOn| (C ^op)

  |FreeCocartesianOn| : Category ℓC (ℓ-max ℓC ℓC')
  |FreeCocartesianOn| = XC ^op

  -- The generators.  `↑ₘSeq` at `C ^op` is exactly functoriality in
  -- the opposite order.
  ηFreeᶜ : Functor C |FreeCocartesianOn|
  ηFreeᶜ .F-ob = ↑
  ηFreeᶜ .F-hom = ↑ₘ
  ηFreeᶜ .F-id = ↑ₘId
  ηFreeᶜ .F-seq f g = ↑ₘSeq g f

  {- The cocartesian structure, spelled out: the finite products of
     `|FreeCartesianOn| (C ^op)` read backwards. -}
  0ᶜ : |FreeCocartesianOn| .ob
  0ᶜ = ⊤

  _+ᶜ_ : |FreeCocartesianOn| .ob → |FreeCocartesianOn| .ob
    → |FreeCocartesianOn| .ob
  _+ᶜ_ = _×_

  ¡ᶜ : ∀ {Γ} → |FreeCocartesianOn| [ 0ᶜ , Γ ]
  ¡ᶜ = !ₑ

  0η : ∀ {Γ} (t : |FreeCocartesianOn| [ 0ᶜ , Γ ]) → t ≡ ¡ᶜ
  0η = ⊤η

  ι₁ : ∀ {Γ Δ} → |FreeCocartesianOn| [ Γ , Γ +ᶜ Δ ]
  ι₁ = π₁

  ι₂ : ∀ {Γ Δ} → |FreeCocartesianOn| [ Δ , Γ +ᶜ Δ ]
  ι₂ = π₂

  [_,_]ᶜ : ∀ {Γ Δ Θ} → |FreeCocartesianOn| [ Γ , Θ ]
    → |FreeCocartesianOn| [ Δ , Θ ] → |FreeCocartesianOn| [ Γ +ᶜ Δ , Θ ]
  [ f , g ]ᶜ = ⟨ f , g ⟩

  +β₁ : ∀ {Γ Δ Θ} {f : |FreeCocartesianOn| [ Γ , Θ ]}
    {g : |FreeCocartesianOn| [ Δ , Θ ]}
    → ι₁ ⋆⟨ |FreeCocartesianOn| ⟩ [ f , g ]ᶜ ≡ f
  +β₁ = ×β₁

  +β₂ : ∀ {Γ Δ Θ} {f : |FreeCocartesianOn| [ Γ , Θ ]}
    {g : |FreeCocartesianOn| [ Δ , Θ ]}
    → ι₂ ⋆⟨ |FreeCocartesianOn| ⟩ [ f , g ]ᶜ ≡ g
  +β₂ = ×β₂

  +η : ∀ {Γ Δ Θ} {t : |FreeCocartesianOn| [ Γ +ᶜ Δ , Θ ]}
    → t ≡ [ ι₁ ⋆⟨ |FreeCocartesianOn| ⟩ t , ι₂ ⋆⟨ |FreeCocartesianOn| ⟩ t ]ᶜ
  +η = ×η


  {- The binary coproducts are the binary products of
     `FreeCartesianOn (C ^op)`.  They are not restated as
     `BinCoProducts |FreeCocartesianOn|`: that type is a family of
     universal elements in `|FreeCocartesianOn| ^op`, which is the
     double opposite of `|FreeCartesianOn| (C ^op)` and so, `Category`
     being a no-eta record, not the same category.  The β/η equations
     above are the same universal property, transport-free. -}

  {- Dually to the cartesian case it is the DOMAIN functor that must
     preserve the structure: two transformations out of a functor
     preserving the finite coproducts that agree on the generators are
     equal, because maps out of `P (A + B)` are determined. -}
  preservesInitialOn : {D : Category ℓD ℓD'}
    → Functor |FreeCocartesianOn| (D ^op) → Type _
  preservesInitialOn P = preservesTerminalOn (C ^op) (unop₂ P)

  preservesBinCoproductsOn : {D : Category ℓD ℓD'}
    → Functor |FreeCocartesianOn| (D ^op) → Type _
  preservesBinCoproductsOn P = preservesBinProductsOn (C ^op) (unop₂ P)

  uniq₂ᶜ : {D : Category ℓD ℓD'}
    {P Q : Functor |FreeCocartesianOn| (D ^op)}
    → preservesInitialOn P → preservesBinCoproductsOn P
    → (σ τ : NatTrans P Q)
    → (∀ c → σ .N-ob (↑ c) ≡ τ .N-ob (↑ c))
    → σ ≡ τ
  uniq₂ᶜ {P = P} {Q = Q} P-0 P-+ σ τ p = unopNT-inj
    (TwoDim.uniq₂ (C ^op) (unop₂ Q) (unop₂ P) P-0 P-+
      (unopNT σ) (unopNT τ) p)

  private
    restr : {D : Category ℓD ℓD'}
      {P Q : Functor |FreeCocartesianOn| (D ^op)}
      → NatIso (P ∘F ηFreeᶜ) (Q ∘F ηFreeᶜ)
      → NatIso (unop₂ Q ∘F ηFree (C ^op)) (unop₂ P ∘F ηFree (C ^op))
    restr ı .trans .N-ob = ı .trans .N-ob
    restr ı .trans .N-hom f = sym (ı .trans .N-hom f)
    restr ı .nIso c .inv = ı .nIso c .inv
    restr ı .nIso c .sec = ı .nIso c .ret
    restr ı .nIso c .ret = ı .nIso c .sec

  uniqᶜ : {D : Category ℓD ℓD'}
    (P Q : Functor |FreeCocartesianOn| (D ^op))
    → preservesInitialOn P → preservesBinCoproductsOn P
    → preservesInitialOn Q → preservesBinCoproductsOn Q
    → NatIso (P ∘F ηFreeᶜ) (Q ∘F ηFreeᶜ)
    → NatIso P Q
  uniqᶜ P Q P-0 P-+ Q-0 Q-+ ı =
    opNatIso (uniq (C ^op) (unop₂ Q) (unop₂ P) Q-0 Q-+ P-0 P-+ (restr ı))

  private
    restrT : {D : Category ℓD ℓD'}
      {P Q : Functor |FreeCocartesianOn| (D ^op)}
      → NatTrans (P ∘F ηFreeᶜ) (Q ∘F ηFreeᶜ)
      → NatTrans (unop₂ Q ∘F ηFree (C ^op)) (unop₂ P ∘F ηFree (C ^op))
    restrT β .N-ob = β .N-ob
    restrT β .N-hom f = sym (β .N-hom f)

  -- Two dimensional recursion.
  rec₂ᶜ : {D : Category ℓD ℓD'}
    (P Q : Functor |FreeCocartesianOn| (D ^op))
    → preservesInitialOn P → preservesBinCoproductsOn P
    → NatTrans (P ∘F ηFreeᶜ) (Q ∘F ηFreeᶜ)
    → NatTrans P Q
  rec₂ᶜ P Q P-0 P-+ β =
    opNT (TwoDim.rec₂ (C ^op) (unop₂ Q) (unop₂ P) P-0 P-+ (restrT β))

  rec₂ᶜ-β : {D : Category ℓD ℓD'}
    (P Q : Functor |FreeCocartesianOn| (D ^op))
    (P-0 : preservesInitialOn P) (P-+ : preservesBinCoproductsOn P)
    (β : NatTrans (P ∘F ηFreeᶜ) (Q ∘F ηFreeᶜ))
    → ∀ c → rec₂ᶜ P Q P-0 P-+ β .N-ob (↑ c) ≡ β .N-ob c
  rec₂ᶜ-β P Q P-0 P-+ β c = refl

  {- A cocartesian category is presented as `CC .Cat ^op` for a
     cartesian category CC.  Restriction along ηFreeᶜ from coproduct
     preserving functors has a section. -}
  module _ (CC : CartesianCategory ℓD ℓD') where
    private module CC = CartesianCategory CC
    module _ (G : Functor C (CC.C ^op)) where
      recᶜ : Functor |FreeCocartesianOn| (CC.C ^op)
      recᶜ = op₂ (rec (C ^op) CC (recOp G))

      recᶜ-β : recᶜ ∘F ηFreeᶜ ≡ G
      recᶜ-β = Functor≡ (λ _ → refl) (λ _ → refl)

      recᶜ-0 : preservesInitialOn recᶜ
      recᶜ-0 = rec-preservesTerminal (C ^op) CC (recOp G)

      recᶜ-+ : preservesBinCoproductsOn recᶜ
      recᶜ-+ = rec-preservesBinProducts (C ^op) CC (recOp G)

-- Functoriality: T₁ᶜ F is the recursive extension of ηFreeᶜ ∘ F.
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} (F : Functor C D) where
  T₁ᶜ : Functor (|FreeCocartesianOn| C) (|FreeCocartesianOn| D)
  T₁ᶜ = recᶜ C (FreeCartesianOn (D ^op)) (ηFreeᶜ D ∘F F)

  T₁ᶜ-0 : preservesInitialOn C T₁ᶜ
  T₁ᶜ-0 = recᶜ-0 C (FreeCartesianOn (D ^op)) (ηFreeᶜ D ∘F F)

  T₁ᶜ-+ : preservesBinCoproductsOn C T₁ᶜ
  T₁ᶜ-+ = recᶜ-+ C (FreeCartesianOn (D ^op)) (ηFreeᶜ D ∘F F)

{- A composite of two recᶜ-generated functors preserves the finite
   coproducts on the nose, just as a single recᶜ does. -}
module _ {A : Category ℓA ℓA'} {B : Category ℓB ℓB'}
         (CC : CartesianCategory ℓE ℓE')
         (G₁ : Functor A (|FreeCocartesianOn| B))
         (G₂ : Functor B (CartesianCategory.C CC ^op)) where
  private module CC = CartesianCategory CC

  recSeqᶜ : Functor (|FreeCocartesianOn| A) (CC.C ^op)
  recSeqᶜ = recᶜ B CC G₂ ∘F recᶜ A (FreeCartesianOn (B ^op)) G₁

  recSeqᶜ-0 : preservesInitialOn A recSeqᶜ
  recSeqᶜ-0 = recSeq-1 CC (recOp G₁) (recOp G₂)

  recSeqᶜ-+ : preservesBinCoproductsOn A recSeqᶜ
  recSeqᶜ-+ = recSeq-× CC (recOp G₁) (recOp G₂)

-- The action of T on 2-cells, by two dimensional recursion.
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} (F G : Functor C D)
  where
  T₂ᶜ : NatTrans F G → NatTrans (T₁ᶜ F) (T₁ᶜ G)
  T₂ᶜ β = rec₂ᶜ C (T₁ᶜ F) (T₁ᶜ G) (T₁ᶜ-0 F) (T₁ᶜ-+ F)
    (natTrans (λ c → ↑ₘ (β .N-ob c))
      (λ f → sym (↑ₘSeq _ _) ∙ cong ↑ₘ (β .N-hom f) ∙ ↑ₘSeq _ _))

  T₂ᶜ-β : (β : NatTrans F G) → ∀ c → T₂ᶜ β .N-ob (↑ c) ≡ ↑ₘ (β .N-ob c)
  T₂ᶜ-β β c = refl

  T₂ᶜ-uniq : (β : NatTrans F G) (σ : NatTrans (T₁ᶜ F) (T₁ᶜ G))
    → (∀ c → σ .N-ob (↑ c) ≡ ↑ₘ (β .N-ob c))
    → σ ≡ T₂ᶜ β
  T₂ᶜ-uniq β σ p = uniq₂ᶜ C (T₁ᶜ-0 F) (T₁ᶜ-+ F) σ (T₂ᶜ β) p

module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} where
  T₂ᶜ-id : (F : Functor C D) → T₂ᶜ F F (idTrans F) ≡ idTrans (T₁ᶜ F)
  T₂ᶜ-id F =
    sym (T₂ᶜ-uniq F F (idTrans F) (idTrans (T₁ᶜ F)) (λ c → sym ↑ₘId))

  T₂ᶜ-seq : (F G H : Functor C D)
    (β : NatTrans F G) (γ : NatTrans G H)
    → T₂ᶜ F H (seqTrans β γ) ≡ seqTrans (T₂ᶜ F G β) (T₂ᶜ G H γ)
  T₂ᶜ-seq F G H β γ = sym (T₂ᶜ-uniq F H (seqTrans β γ)
    (seqTrans (T₂ᶜ F G β) (T₂ᶜ G H γ)) (λ c → sym (↑ₘSeq _ _)))

  -- the action of T on hom-categories
  TFunᶜ : Functor (FUNCTOR C D)
                  (FUNCTOR (|FreeCocartesianOn| C) (|FreeCocartesianOn| D))
  TFunᶜ .F-ob = T₁ᶜ
  TFunᶜ .F-hom {x = F} {y = G} = T₂ᶜ F G
  TFunᶜ .F-id {x = F} = T₂ᶜ-id F
  TFunᶜ .F-seq β γ = T₂ᶜ-seq _ _ _ β γ

module _ {C : Category ℓC ℓC'} where
  private
    FC = FreeCartesianOn (C ^op)
    module FC = Category (|FreeCocartesianOn| C)

  T₁ᶜ-id : NatIso (T₁ᶜ (Id {C = C})) Id
  T₁ᶜ-id = uniqᶜ C (T₁ᶜ Id) Id (T₁ᶜ-0 Id) (T₁ᶜ-+ Id)
    (idPreservesTerminal' (FC .term))
    (idPreservesBinProducts (FC .bp)) ı≅ where
    ı≅ : NatIso (T₁ᶜ (Id {C = C}) ∘F ηFreeᶜ C) (Id ∘F ηFreeᶜ C)
    ı≅ .trans .N-ob x = FC.id
    ı≅ .trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd

module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} {E : Category ℓE ℓE'}
         (F : Functor C D) (G : Functor D E) where
  private
    FE = FreeCartesianOn (E ^op)
    module FE = Category (|FreeCocartesianOn| E)

  T₁ᶜ-seq : NatIso (T₁ᶜ (G ∘F F)) (T₁ᶜ G ∘F T₁ᶜ F)
  T₁ᶜ-seq = uniqᶜ C (T₁ᶜ (G ∘F F)) (T₁ᶜ G ∘F T₁ᶜ F)
    (T₁ᶜ-0 (G ∘F F)) (T₁ᶜ-+ (G ∘F F))
    (recSeqᶜ-0 FE (ηFreeᶜ D ∘F F) (ηFreeᶜ E ∘F G))
    (recSeqᶜ-+ FE (ηFreeᶜ D ∘F F) (ηFreeᶜ E ∘F G)) ı≅ where
    ı≅ : NatIso (T₁ᶜ (G ∘F F) ∘F ηFreeᶜ C) ((T₁ᶜ G ∘F T₁ᶜ F) ∘F ηFreeᶜ C)
    ı≅ .trans .N-ob x = FE.id
    ı≅ .trans .N-hom f = FE.⋆IdR _ ∙ sym (FE.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd

-- The multiplication: |FreeCocartesianOn| C is already cocartesian,
-- so the identity extends to it.
module _ (C : Category ℓC ℓC') where
  μFreeᶜ : Functor (|FreeCocartesianOn| (|FreeCocartesianOn| C))
                   (|FreeCocartesianOn| C)
  μFreeᶜ = recᶜ (|FreeCocartesianOn| C) (FreeCartesianOn (C ^op)) Id

  μFreeᶜ-0 : preservesInitialOn (|FreeCocartesianOn| C) μFreeᶜ
  μFreeᶜ-0 = recᶜ-0 (|FreeCocartesianOn| C) (FreeCartesianOn (C ^op)) Id

  μFreeᶜ-+ : preservesBinCoproductsOn (|FreeCocartesianOn| C) μFreeᶜ
  μFreeᶜ-+ = recᶜ-+ (|FreeCocartesianOn| C) (FreeCartesianOn (C ^op)) Id

-- The monad laws, as natural isomorphisms of the underlying functors.
module _ (C : Category ℓC ℓC') where
  private
    TC = |FreeCocartesianOn| C
    T²C = |FreeCocartesianOn| TC
    FC = FreeCartesianOn (C ^op)
    module FC = Category TC

  μ-ηRᶜ : μFreeᶜ C ∘F ηFreeᶜ TC ≡ Id
  μ-ηRᶜ = recᶜ-β TC FC Id

  μ-ηLᶜ : NatIso (μFreeᶜ C ∘F T₁ᶜ (ηFreeᶜ C)) Id
  μ-ηLᶜ = uniqᶜ C (μFreeᶜ C ∘F T₁ᶜ (ηFreeᶜ C)) Id
    (recSeqᶜ-0 FC (ηFreeᶜ TC ∘F ηFreeᶜ C) Id)
    (recSeqᶜ-+ FC (ηFreeᶜ TC ∘F ηFreeᶜ C) Id)
    (idPreservesTerminal' (FC .term))
    (idPreservesBinProducts (FC .bp)) ı≅ where
    ı≅ : NatIso ((μFreeᶜ C ∘F T₁ᶜ (ηFreeᶜ C)) ∘F ηFreeᶜ C) (Id ∘F ηFreeᶜ C)
    ı≅ .trans .N-ob x = FC.id
    ı≅ .trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd

  μ-assocᶜ : NatIso (μFreeᶜ C ∘F T₁ᶜ (μFreeᶜ C)) (μFreeᶜ C ∘F μFreeᶜ TC)
  μ-assocᶜ = uniqᶜ T²C (μFreeᶜ C ∘F T₁ᶜ (μFreeᶜ C)) (μFreeᶜ C ∘F μFreeᶜ TC)
    (recSeqᶜ-0 FC (ηFreeᶜ TC ∘F μFreeᶜ C) Id)
    (recSeqᶜ-+ FC (ηFreeᶜ TC ∘F μFreeᶜ C) Id)
    (recSeqᶜ-0 FC Id Id) (recSeqᶜ-+ FC Id Id) ı≅ where
    ı≅ : NatIso ((μFreeᶜ C ∘F T₁ᶜ (μFreeᶜ C)) ∘F ηFreeᶜ T²C)
                ((μFreeᶜ C ∘F μFreeᶜ TC) ∘F ηFreeᶜ T²C)
    ı≅ .trans .N-ob x = FC.id
    ı≅ .trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd

-- Naturality of η (strict) and of μ (up to natural isomorphism).
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} (F : Functor C D) where
  private
    TC = |FreeCocartesianOn| C
    TD = |FreeCocartesianOn| D
    FD = FreeCartesianOn (D ^op)
    module FD = Category TD

  ηFreeᶜ-nat : T₁ᶜ F ∘F ηFreeᶜ C ≡ ηFreeᶜ D ∘F F
  ηFreeᶜ-nat = recᶜ-β C FD (ηFreeᶜ D ∘F F)

  μFreeᶜ-nat : NatIso (μFreeᶜ D ∘F T₁ᶜ (T₁ᶜ F)) (T₁ᶜ F ∘F μFreeᶜ C)
  μFreeᶜ-nat = uniqᶜ TC (μFreeᶜ D ∘F T₁ᶜ (T₁ᶜ F)) (T₁ᶜ F ∘F μFreeᶜ C)
    (recSeqᶜ-0 FD (ηFreeᶜ TD ∘F T₁ᶜ F) Id)
    (recSeqᶜ-+ FD (ηFreeᶜ TD ∘F T₁ᶜ F) Id)
    (recSeqᶜ-0 FD Id (ηFreeᶜ D ∘F F))
    (recSeqᶜ-+ FD Id (ηFreeᶜ D ∘F F)) ı≅ where
    ı≅ : NatIso ((μFreeᶜ D ∘F T₁ᶜ (T₁ᶜ F)) ∘F ηFreeᶜ TC)
                ((T₁ᶜ F ∘F μFreeᶜ C) ∘F ηFreeᶜ TC)
    ı≅ .trans .N-ob x = FD.id
    ı≅ .trans .N-hom f = FD.⋆IdR _ ∙ sym (FD.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd
