{- Free monoidal category generated by a category -}
{-# OPTIONS --lossy-unification #-}
module Cubical.Categories.Instances.Free.Monoidal.OnCategory where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Unit
open import Cubical.Data.Sigma

open import Cubical.Categories.Category.Base
open import Cubical.Categories.Isomorphism
open import Cubical.Categories.Monoidal.Base
open import Cubical.Categories.Monoidal.Functor
open import Cubical.Categories.Functor
open import Cubical.Categories.NaturalTransformation
open import Cubical.Categories.Instances.BinProduct
open import Cubical.Categories.Instances.Functors

open import Cubical.Categories.Displayed.Base
open import Cubical.Categories.Displayed.HLevels
open import Cubical.Categories.Displayed.More
open import Cubical.Categories.Displayed.Functor
open import Cubical.Categories.Displayed.NaturalTransformation
open import Cubical.Categories.Displayed.NaturalTransformation.More
open import Cubical.Categories.Displayed.Section
open import Cubical.Categories.Displayed.Monoidal.Base
open import Cubical.Categories.Displayed.Instances.Reindex.Base
  as Monoidal
open import Cubical.Categories.Displayed.Instances.Reindex.Properties
open import Cubical.Categories.Displayed.Instances.Weaken.Monoidal
import Cubical.Categories.Displayed.Instances.Weaken as Wk
open import Cubical.Categories.Displayed.Instances.Arrow.Base
open import Cubical.Categories.Displayed.Instances.Arrow.Monoidal

private
  variable
    ℓ ℓC ℓC' ℓD ℓD' ℓE ℓE' : Level

open Category
open Functor
open NatTrans
open NatIso
open NatTransᴰ
open NatIsoᴰ
open isIso
open isIsoᴰ
open Section
open Functorᴰ


module _ (C : Category ℓC ℓC') where
  private module C = Category C

  data MonOb : Type ℓC where
    ↑ : C .ob → MonOb
    unit : MonOb
    _⊗_ : MonOb → MonOb → MonOb

  data MonMor : MonOb → MonOb → Type (ℓ-max ℓC ℓC') where
    idₑ : ∀ {x} → MonMor x x
    _⋆ₑ_ : ∀ {x y z} → MonMor x y → MonMor y z → MonMor x z
    ⋆ₑIdL : ∀ {x y} (e : MonMor x y) → idₑ ⋆ₑ e ≡ e
    ⋆ₑIdR : ∀ {x y} (e : MonMor x y) → e ⋆ₑ idₑ ≡ e
    ⋆ₑAssoc : ∀ {x y z D} (e : MonMor x y)(f : MonMor y z)(g : MonMor z D)
              → (e ⋆ₑ f) ⋆ₑ g ≡ e ⋆ₑ (f ⋆ₑ g)
    isSetHomₑ : ∀ {x y} → isSet (MonMor x y)

    ↑ₘ : ∀ {x y} → C [ x , y ] → MonMor (↑ x) (↑ y)
    ↑ₘId : ∀ {x} → ↑ₘ (C .id {x}) ≡ idₑ
    ↑ₘSeq : ∀ {x y z} (f : C [ x , y ]) (g : C [ y , z ])
          → ↑ₘ (f ⋆⟨ C ⟩ g) ≡ ↑ₘ f ⋆ₑ ↑ₘ g

    _⊗_ : ∀ {x x' y y'} → MonMor x y → MonMor x' y' → MonMor (x ⊗ x') (y ⊗ y')
    ⊗id : ∀ {x y} → idₑ ⊗ idₑ ≡ idₑ {x ⊗ y}
    ⊗⋆  : ∀ {x x' y y' z z'}
      (f : MonMor x y) (g : MonMor y z)
      (f' : MonMor x' y') (g' : MonMor y' z')
      → (f ⋆ₑ g) ⊗ (f' ⋆ₑ g') ≡ ((f ⊗ f') ⋆ₑ (g ⊗ g'))

    α : ∀ {x y z} → MonMor (x ⊗ (y ⊗ z)) ((x ⊗ y) ⊗ z)
    α⁻ : ∀ {x y z} → MonMor ((x ⊗ y) ⊗ z) (x ⊗ (y ⊗ z))
    α-nat : ∀ {x x' y y' z z'} →
      (f : MonMor x x')(g : MonMor y y')(h : MonMor z z')
      → ((f ⊗ (g ⊗ h)) ⋆ₑ α) ≡ (α ⋆ₑ ((f ⊗ g) ⊗ h))
    α⋆α⁻ : ∀ {x y z} → α {x}{y}{z} ⋆ₑ α⁻ ≡ idₑ
    α⁻⋆α : ∀ {x y z} → α⁻ {x}{y}{z} ⋆ₑ α ≡ idₑ

    η : ∀ {x} → MonMor (unit ⊗ x) x
    η⁻ : ∀ {x} → MonMor x (unit ⊗ x)
    η-nat : ∀ {x y} (f : MonMor x y) → ((idₑ ⊗ f) ⋆ₑ η) ≡ (η ⋆ₑ f)
    η⋆η⁻ : ∀ {x} → (η {x} ⋆ₑ η⁻) ≡ idₑ
    η⁻⋆η : ∀ {x} → (η⁻ {x} ⋆ₑ η) ≡ idₑ

    ρ : ∀ {x} → MonMor (x ⊗ unit) x
    ρ⁻ : ∀ {x} → MonMor x (x ⊗ unit)
    ρ-nat : ∀ {x y} (f : MonMor x y) → ((f ⊗ idₑ) ⋆ₑ ρ) ≡ (ρ ⋆ₑ f)
    ρ⋆ρ⁻ : ∀ {x} → (ρ {x} ⋆ₑ ρ⁻) ≡ idₑ
    ρ⁻⋆ρ : ∀ {x} → (ρ⁻ {x} ⋆ₑ ρ) ≡ idₑ

    pentagon : ∀ {w x y z} →
      (idₑ {w} ⊗ α {x}{y}{z}) ⋆ₑ (α ⋆ₑ (α ⊗ idₑ)) ≡ (α ⋆ₑ α)
    triangle : ∀ {x y} → α ⋆ₑ (ρ {x} ⊗ idₑ) ≡ (idₑ ⊗ (η {y}))

  |FreeMonoidalOn| : Category ℓC (ℓ-max ℓC ℓC')
  |FreeMonoidalOn| .ob = MonOb
  |FreeMonoidalOn| .Hom[_,_] = MonMor
  |FreeMonoidalOn| .id = idₑ
  |FreeMonoidalOn| ._⋆_ = _⋆ₑ_
  |FreeMonoidalOn| .⋆IdL = ⋆ₑIdL
  |FreeMonoidalOn| .⋆IdR = ⋆ₑIdR
  |FreeMonoidalOn| .⋆Assoc = ⋆ₑAssoc
  |FreeMonoidalOn| .isSetHom = isSetHomₑ

  FreeMonoidalOnStr : TensorStr |FreeMonoidalOn|
  FreeMonoidalOnStr .TensorStr.─⊗─ .F-ob (x , y) = x ⊗ y
  FreeMonoidalOnStr .TensorStr.─⊗─ .F-hom (f , g) = f ⊗ g
  FreeMonoidalOnStr .TensorStr.─⊗─ .F-id = ⊗id
  FreeMonoidalOnStr .TensorStr.─⊗─ .F-seq f g =
    ⊗⋆ (f .fst) (g .fst) (f .snd) (g .snd)
  FreeMonoidalOnStr .TensorStr.unit = unit

  FreeMonoidalOn : MonoidalCategory ℓC (ℓ-max ℓC ℓC')
  FreeMonoidalOn .MonoidalCategory.C = |FreeMonoidalOn|
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.tenstr =
    FreeMonoidalOnStr
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.α .trans .N-ob x = α
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.α .trans .N-hom f =
    α-nat _ _ _
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.α .nIso x .inv = α⁻
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.α .nIso x .sec = α⁻⋆α
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.α .nIso x .ret = α⋆α⁻
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.η .trans .N-ob x = η
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.η .trans .N-hom = η-nat
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.η .nIso x .inv = η⁻
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.η .nIso x .sec = η⁻⋆η
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.η .nIso x .ret = η⋆η⁻
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.ρ .trans .N-ob x = ρ
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.ρ .trans .N-hom = ρ-nat
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.ρ .nIso x .inv = ρ⁻
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.ρ .nIso x .sec = ρ⁻⋆ρ
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.ρ .nIso x .ret = ρ⋆ρ⁻
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.pentagon w x y z =
    pentagon
  FreeMonoidalOn .MonoidalCategory.monstr .MonoidalStr.triangle x y = triangle

  ηFree : Functor C |FreeMonoidalOn|
  ηFree .F-ob = ↑
  ηFree .F-hom = ↑ₘ
  ηFree .F-id = ↑ₘId
  ηFree .F-seq = ↑ₘSeq

  -- Elimination: a section of a displayed monoidal category over
  -- FreeMonoidalOn along ηFree extends to a global section.
  module _ (Mᴰ : MonoidalCategoryᴰ FreeMonoidalOn ℓD ℓD') where
    private
      module Mᴰ = MonoidalCategoryᴰ Mᴰ
    module _ (ı : Section ηFree Mᴰ.Cᴰ) where
      private module ı = Section ı

      elim-ob : ∀ x → Mᴰ.ob[ x ]
      elim-ob (↑ x) = ı.F-obᴰ x
      elim-ob unit = Mᴰ.unitᴰ
      elim-ob (x ⊗ y) = elim-ob x Mᴰ.⊗ᴰ elim-ob y

      elim-hom : ∀ {x y}(f : |FreeMonoidalOn| [ x , y ])
        → Mᴰ.Hom[ f ][ elim-ob x , elim-ob y ]
      elim-hom idₑ = Mᴰ.idᴰ
      elim-hom (f ⋆ₑ g) = elim-hom f Mᴰ.⋆ᴰ elim-hom g
      elim-hom (⋆ₑIdL f i) = Mᴰ.⋆IdLᴰ (elim-hom f) i
      elim-hom (⋆ₑIdR f i) = Mᴰ.⋆IdRᴰ (elim-hom f) i
      elim-hom (⋆ₑAssoc f g h i) =
        Mᴰ.⋆Assocᴰ (elim-hom f)(elim-hom g)(elim-hom h) i
      elim-hom (isSetHomₑ f g p q i j) =
        isSetHomᴰ' Mᴰ.Cᴰ
          (elim-hom f) (elim-hom g)
          (cong elim-hom p) (cong elim-hom q)
          i j
      elim-hom (↑ₘ f) = ı.F-homᴰ f
      elim-hom (↑ₘId i) = ı.F-idᴰ i
      elim-hom (↑ₘSeq f g i) = ı.F-seqᴰ f g i
      elim-hom (f ⊗ g) = elim-hom f Mᴰ.⊗ₕᴰ elim-hom g
      elim-hom (⊗id i) = Mᴰ.─⊗ᴰ─ .F-idᴰ i
      elim-hom (⊗⋆ f g f' g' i) =
        Mᴰ.─⊗ᴰ─ .F-seqᴰ
          ((elim-hom f) , (elim-hom f'))
          (elim-hom g , elim-hom g')
          i
      elim-hom α = Mᴰ.αᴰ⟨ _ , _ , _ ⟩
      elim-hom (α-nat f g h i) =
        Mᴰ.αᴰ .transᴰ .N-homᴰ ((elim-hom f) , (elim-hom g) , (elim-hom h)) i
      elim-hom α⁻ = Mᴰ.αᴰ .nIsoᴰ _ .invᴰ
      elim-hom (α⋆α⁻ i) = Mᴰ.αᴰ .nIsoᴰ _ .retᴰ i
      elim-hom (α⁻⋆α i) = Mᴰ.αᴰ .nIsoᴰ _ .secᴰ i
      elim-hom η = Mᴰ.ηᴰ⟨ _ ⟩
      elim-hom (η-nat f i) = Mᴰ.ηᴰ .transᴰ .N-homᴰ (elim-hom f) i
      elim-hom η⁻ = Mᴰ.ηᴰ .nIsoᴰ _ .invᴰ
      elim-hom (η⋆η⁻ i) = Mᴰ.ηᴰ .nIsoᴰ _ .retᴰ i
      elim-hom (η⁻⋆η i) = Mᴰ.ηᴰ .nIsoᴰ _ .secᴰ i
      elim-hom ρ = Mᴰ.ρᴰ⟨ _ ⟩
      elim-hom (ρ-nat f i) = Mᴰ.ρᴰ .transᴰ .N-homᴰ (elim-hom f) i
      elim-hom ρ⁻ = Mᴰ.ρᴰ .nIsoᴰ _ .invᴰ
      elim-hom (ρ⋆ρ⁻ i) = Mᴰ.ρᴰ .nIsoᴰ _ .retᴰ i
      elim-hom (ρ⁻⋆ρ i) = Mᴰ.ρᴰ .nIsoᴰ _ .secᴰ i
      elim-hom (pentagon i) = Mᴰ.pentagonᴰ _ _ _ _ i
      elim-hom (triangle i) = Mᴰ.triangleᴰ _ _ i

      elim : GlobalSection Mᴰ.Cᴰ
      elim .F-obᴰ = elim-ob
      elim .F-homᴰ = elim-hom
      elim .F-idᴰ = refl
      elim .F-seqᴰ _ _ = refl

  -- Universal property: restriction along ηFree from strong monoidal
  -- functors into M to functors into M.C has a section (rec), and is
  -- injective up to natural isomorphism (uniq).
  module _ (M : MonoidalCategory ℓD ℓD') where
    private
      module M = MonoidalCategory M
    module _ (G : Functor C M.C) where
      private
        Mᴰ = weaken FreeMonoidalOn M
        module Mᴰ = MonoidalCategoryᴰ Mᴰ
      open StrongMonoidalFunctor
      open StrongMonoidalStr
      open LaxMonoidalStr

      rec : StrongMonoidalFunctor FreeMonoidalOn M
      rec .F = Wk.introS⁻ (elim Mᴰ (Wk.introS ηFree G))
      rec .strmonstr .laxmonstr .ε = M.id
      rec .strmonstr .laxmonstr .μ .N-ob x = M.id
      rec .strmonstr .laxmonstr .μ .N-hom f =
        M.⋆IdR _ ∙ sym (M.⋆IdL _)
      rec .strmonstr .laxmonstr .αμ-law x y z =
        M.⋆IdR _
        ∙ cong₂ M._⋆_ refl (M.─⊗─ .F-id)
        ∙ M.⋆IdR _ ∙ sym (M.⋆IdL _)
        ∙ cong₂ M._⋆_ (sym (M.─⊗─ .F-id)) refl
        ∙ cong₂ M._⋆_ (sym (M.⋆IdR _)) refl
      rec .strmonstr .laxmonstr .ηε-law x =
        cong₂ M._⋆_ (M.⋆IdR _ ∙ M.─⊗─ .F-id) refl ∙ M.⋆IdL _
      rec .strmonstr .laxmonstr .ρε-law x =
        cong₂ M._⋆_ (M.⋆IdR _ ∙ M.─⊗─ .F-id) refl ∙ M.⋆IdL _
      rec .strmonstr .ε-isIso = idCatIso .snd
      rec .strmonstr .μ-isIso _ = idCatIso .snd

      -- rec extends G along ηFree, strictly on obs and homs
      rec-β : rec .F ∘F ηFree ≡ G
      rec-β = Functor≡ (λ _ → refl) (λ _ → refl)

    module _ (G H : StrongMonoidalFunctor FreeMonoidalOn M) where
      private
        module G = StrongMonoidalFunctor G
        module H = StrongMonoidalFunctor H
        module IC = MonoidalCategoryᴰ (IsoComma G H)
      uniq : (ı≅ : (G.F ∘F ηFree) ≅ᶜ (H.F ∘F ηFree)) → G.F ≅ᶜ H.F
      uniq ı≅ = IsoReflection (GlobalSectionReindex→Section _ _
        (elim (IsoComma G H) S))
        where
          hasPropHomsIC : hasPropHoms IC.Cᴰ
          hasPropHomsIC f = hasPropHomsIso M.C _

          S : Section ηFree IC.Cᴰ
          S = mkPropHomsSection hasPropHomsIC
            (λ x → ı≅ .trans .N-ob x , ı≅ .nIso x)
            (λ f → ı≅ .trans .N-hom f , tt)

      -- 2-dimensional uniqueness: a monoidal natural transformation
      -- out of the free monoidal category is determined by its
      -- restriction along ηFree.  The two transformations are
      -- implicit: at a use site they are read off the goal rather
      -- than respelled, which keeps their naturality proofs out of
      -- the comparison the use site would otherwise force.
      uniq₂ : {σ τ : NatTrans G.F H.F}
        → isMonoidalNat G H σ → isMonoidalNat G H τ
        → (∀ c → σ .N-ob (↑ c) ≡ τ .N-ob (↑ c))
        → σ ≡ τ
      uniq₂ {σ} {τ} mσ mτ p↑ = makeNatTransPath (funExt go) where
        go : ∀ x → σ .N-ob x ≡ τ .N-ob x
        go (↑ c) = p↑ c
        go unit = ⋆CancelL G.ε-Iso (mσ .fst ∙ sym (mτ .fst))
        go (x ⊗ y) = ⋆CancelL (G.μ⟨ x , y ⟩ , G.μ-isIso (x , y))
          (mσ .snd x y
          ∙ cong₂ M._⋆_ (cong₂ M._⊗ₕ_ (go x) (go y)) refl
          ∙ sym (mτ .snd x y))

      -- The comparison produced by uniq is monoidal: its components
      -- at unit and at x ⊗ y are the ε and μ conjugates.
      uniq-isMonoidal : (ı≅ : (G.F ∘F ηFree) ≅ᶜ (H.F ∘F ηFree))
        → isMonoidalNat G H (uniq ı≅ .trans)
      uniq-isMonoidal ı≅ .fst =
        sym (M.⋆Assoc _ _ _)
        ∙ cong₂ M._⋆_ (G.ε-isIso .ret) refl
        ∙ M.⋆IdL _ ∙ M.⋆IdL _
      uniq-isMonoidal ı≅ .snd x y =
        sym (M.⋆Assoc _ _ _)
        ∙ cong₂ M._⋆_ (G.μ-isIso _ .ret) refl
        ∙ M.⋆IdL _

      -- 2-dimensional recursion: every natural transformation between
      -- the restrictions extends to a monoidal one.  Unlike uniq this
      -- needs no invertibility, since ArrowComma is the comma object
      -- for arbitrary 2-cells.
      private
        module AC = MonoidalCategoryᴰ (ArrowComma G H)
        hasPropHomsAC : hasPropHoms AC.Cᴰ
        hasPropHomsAC f = hasPropHomsArrow M.C _

      rec₂ : (β : NatTrans (G.F ∘F ηFree) (H.F ∘F ηFree))
        → NatTrans G.F H.F
      rec₂ β = ArrowReflection (GlobalSectionReindex→Section _ _
        (elim (ArrowComma G H) S))
        where
          S : Section ηFree AC.Cᴰ
          S = mkPropHomsSection hasPropHomsAC (β .N-ob) (β .N-hom)

      rec₂-isMonoidal : (β : NatTrans (G.F ∘F ηFree) (H.F ∘F ηFree))
        → isMonoidalNat G H (rec₂ β)
      rec₂-isMonoidal β .fst =
        sym (M.⋆Assoc _ _ _)
        ∙ cong₂ M._⋆_ (G.ε-isIso .ret) refl
        ∙ M.⋆IdL _ ∙ M.⋆IdL _
      rec₂-isMonoidal β .snd x y =
        sym (M.⋆Assoc _ _ _)
        ∙ cong₂ M._⋆_ (G.μ-isIso _ .ret) refl
        ∙ M.⋆IdL _

      rec₂-β : (β : NatTrans (G.F ∘F ηFree) (H.F ∘F ηFree))
        → ∀ c → rec₂ β .N-ob (↑ c) ≡ β .N-ob c
      rec₂-β β c = refl


-- Functoriality: T₁ F is the recursive extension of ↑ ∘ F.
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} (F : Functor C D) where
  T₁Str : StrongMonoidalFunctor (FreeMonoidalOn C) (FreeMonoidalOn D)
  T₁Str = rec C (FreeMonoidalOn D) (ηFree D ∘F F)

  T₁ : Functor (|FreeMonoidalOn| C) (|FreeMonoidalOn| D)
  T₁ = T₁Str .StrongMonoidalFunctor.F

module _ {C : Category ℓC ℓC'} where
  private
    FC = FreeMonoidalOn C
    module FC = MonoidalCategory FC

  T₁-id : T₁ (Id {C = C}) ≅ᶜ Id
  T₁-id = uniq C FC (T₁Str Id) IdStr ı≅ where
    ı≅ : (T₁ (Id {C = C}) ∘F ηFree C) ≅ᶜ (Id ∘F ηFree C)
    ı≅ .trans .N-ob x = FC.id
    ı≅ .trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd

{- A composite of two rec-generated functors preserves ⊗, unit, α, η
   and ρ on the nose, so it is strong monoidal with identity
   comparison maps: the laws are exactly `rec`'s. -}
module _ {A : Category ℓC ℓC'} {B : Category ℓD ℓD'}
         (M : MonoidalCategory ℓE ℓE')
         (G₁ : Functor A (|FreeMonoidalOn| B))
         (G₂ : Functor B (M .MonoidalCategory.C)) where
  private module M = MonoidalCategory M
  open StrongMonoidalFunctor
  open StrongMonoidalStr
  open LaxMonoidalStr

  recSeqStr : StrongMonoidalFunctor (FreeMonoidalOn A) M
  recSeqStr .F = rec B M G₂ .F ∘F rec A (FreeMonoidalOn B) G₁ .F
  recSeqStr .strmonstr .laxmonstr .ε = M.id
  recSeqStr .strmonstr .laxmonstr .μ .N-ob x = M.id
  recSeqStr .strmonstr .laxmonstr .μ .N-hom f = M.⋆IdR _ ∙ sym (M.⋆IdL _)
  recSeqStr .strmonstr .laxmonstr .αμ-law x y z =
    M.⋆IdR _
    ∙ cong₂ M._⋆_ refl (M.─⊗─ .F-id)
    ∙ M.⋆IdR _ ∙ sym (M.⋆IdL _)
    ∙ cong₂ M._⋆_ (sym (M.─⊗─ .F-id)) refl
    ∙ cong₂ M._⋆_ (sym (M.⋆IdR _)) refl
  recSeqStr .strmonstr .laxmonstr .ηε-law x =
    cong₂ M._⋆_ (M.⋆IdR _ ∙ M.─⊗─ .F-id) refl ∙ M.⋆IdL _
  recSeqStr .strmonstr .laxmonstr .ρε-law x =
    cong₂ M._⋆_ (M.⋆IdR _ ∙ M.─⊗─ .F-id) refl ∙ M.⋆IdL _
  recSeqStr .strmonstr .ε-isIso = idCatIso .snd
  recSeqStr .strmonstr .μ-isIso _ = idCatIso .snd

module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} {E : Category ℓE ℓE'}
         (F₁ : Functor C D) (G₁ : Functor D E) where
  private
    FE = FreeMonoidalOn E
    module FE = MonoidalCategory FE

  T₁∘Str : StrongMonoidalFunctor (FreeMonoidalOn C) FE
  T₁∘Str = recSeqStr FE (ηFree D ∘F F₁) (ηFree E ∘F G₁)

  T₁-seq : T₁ (G₁ ∘F F₁) ≅ᶜ (T₁ G₁ ∘F T₁ F₁)
  T₁-seq = uniq C FE (T₁Str (G₁ ∘F F₁)) T₁∘Str ı≅ where
    ı≅ : (T₁ (G₁ ∘F F₁) ∘F ηFree C) ≅ᶜ ((T₁ G₁ ∘F T₁ F₁) ∘F ηFree C)
    ı≅ .trans .N-ob x = FE.id
    ı≅ .trans .N-hom f = FE.⋆IdR _ ∙ sym (FE.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd

{- The functors T₁ F preserve the monoidal structure definitionally,
   so the arrow category comparing two of them is displayed monoidal
   with no transports: its structure maps are the naturality squares
   of the target's α, η, ρ.  Sections of it are natural
   transformations T₁ F ⇒ T₁ G. -}
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'}
         (F₁ G₁ : Functor C D) where
  private
    FC = FreeMonoidalOn C
    FD = FreeMonoidalOn D
    module FC = MonoidalCategory FC
    module FD = MonoidalCategory FD
    P = T₁ F₁
    Q = T₁ G₁
    Aᴰ = reindex (Arrow FD.C) (P ,F Q)
    hasPropHomsAᴰ : hasPropHoms Aᴰ
    hasPropHomsAᴰ f = hasPropHomsArrow FD.C _

  T₂Motive : MonoidalCategoryᴰ FC (ℓ-max ℓD ℓD') (ℓ-max ℓD ℓD')
  T₂Motive .MonoidalCategoryᴰ.Cᴰ = Aᴰ
  T₂Motive .MonoidalCategoryᴰ.monstrᴰ =
    TensorPropᴰ→TensorStrᴰ FC Aᴰ hasPropHomsAᴰ MP
    where
      open TensorStrᴰ
      open MonoidalPropᴰ
      MP : MonoidalPropᴰ FC Aᴰ
      MP .tenstrᴰ .unitᴰ = FD.id
      MP .tenstrᴰ .─⊗ᴰ─ = mkPropHomsFunctor hasPropHomsAᴰ
        (λ { (r , s) → r FD.⊗ₕ s })
        (λ { (p , q) →
          sym (FD.─⊗─ .F-seq _ _)
          ∙ cong₂ FD._⊗ₕ_ p q
          ∙ FD.─⊗─ .F-seq _ _ })
      MP .αᴰ⟨_,_,_⟩ _ _ _ = sym (FD.α .trans .N-hom _)
      MP .α⁻¹ᴰ⟨_,_,_⟩ _ _ _ = sym (symNatIso FD.α .trans .N-hom _)
      MP .ηᴰ⟨_⟩ _ = sym (FD.η .trans .N-hom _)
      MP .η⁻¹ᴰ⟨_⟩ _ = sym (symNatIso FD.η .trans .N-hom _)
      MP .ρᴰ⟨_⟩ _ = sym (FD.ρ .trans .N-hom _)
      MP .ρ⁻¹ᴰ⟨_⟩ _ = sym (symNatIso FD.ρ .trans .N-hom _)

  T₂ : NatTrans F₁ G₁ → NatTrans P Q
  T₂ β = ArrowReflection (GlobalSectionReindex→Section _ _
    (elim C T₂Motive S))
    where
      S : Section (ηFree C) Aᴰ
      S = mkPropHomsSection hasPropHomsAᴰ
        (λ x → ↑ₘ (β .N-ob x))
        (λ f → sym (↑ₘSeq _ _) ∙ cong ↑ₘ (β .N-hom f) ∙ ↑ₘSeq _ _)

  -- T₂'s components are strict: T₁'s ε and μ are identities and
  -- T₂Motive's ⊗ᴰ is the tensor itself, with no lifts in between.
  T₂-isMonoidal : (β : NatTrans F₁ G₁)
    → isMonoidalNat (T₁Str F₁) (T₁Str G₁) (T₂ β)
  T₂-isMonoidal β .fst = FD.⋆IdL _
  T₂-isMonoidal β .snd x y = FD.⋆IdL _ ∙ sym (FD.⋆IdR _)

  -- Two monoidal natural transformations T₁ F₁ ⇒ T₁ G₁ agreeing on ↑
  -- are equal.
  T₂-uniq : (β : NatTrans F₁ G₁) (σ : NatTrans P Q)
    → isMonoidalNat (T₁Str F₁) (T₁Str G₁) σ
    → (∀ c → σ .N-ob (↑ c) ≡ ↑ₘ (β .N-ob c))
    → σ ≡ T₂ β
  T₂-uniq β σ mσ p = uniq₂ C (FreeMonoidalOn D)
    (T₁Str F₁) (T₁Str G₁) mσ (T₂-isMonoidal β) p

module _ {C : Category ℓC ℓC'} where
  MonObInd : ∀ {ℓ} (Pr : MonOb C → Type ℓ)
    → (∀ c → Pr (↑ c)) → Pr unit
    → (∀ {x y} → Pr x → Pr y → Pr (x ⊗ y))
    → ∀ x → Pr x
  MonObInd Pr p↑ pu p⊗ (↑ c) = p↑ c
  MonObInd Pr p↑ pu p⊗ unit = pu
  MonObInd Pr p↑ pu p⊗ (x ⊗ y) =
    p⊗ (MonObInd Pr p↑ pu p⊗ x) (MonObInd Pr p↑ pu p⊗ y)

-- T₂ is functorial: its components are defined by recursion on MonOb,
-- and they preserve ⊗ and unit definitionally, so induction suffices.
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} where
  private
    module FD = MonoidalCategory (FreeMonoidalOn D)

  T₂-id : (F₁ : Functor C D) → T₂ F₁ F₁ (idTrans F₁) ≡ idTrans (T₁ F₁)
  T₂-id F₁ = makeNatTransPath (funExt
    (MonObInd (λ x → T₂ F₁ F₁ (idTrans F₁) .N-ob x ≡ idTrans (T₁ F₁) .N-ob x)
      (λ c → ↑ₘId) refl
      (λ p q → cong₂ FD._⊗ₕ_ p q ∙ ⊗id)))

  T₂-seq : (F₁ G₁ H₁ : Functor C D)
    (β : NatTrans F₁ G₁)(γ : NatTrans G₁ H₁)
    → T₂ F₁ H₁ (seqTrans β γ) ≡ seqTrans (T₂ F₁ G₁ β) (T₂ G₁ H₁ γ)
  T₂-seq F₁ G₁ H₁ β γ = makeNatTransPath (funExt
    (MonObInd
      (λ x → T₂ F₁ H₁ (seqTrans β γ) .N-ob x
           ≡ seqTrans (T₂ F₁ G₁ β) (T₂ G₁ H₁ γ) .N-ob x)
      (λ c → ↑ₘSeq _ _) (sym (FD.⋆IdL _))
      (λ p q → cong₂ FD._⊗ₕ_ p q ∙ ⊗⋆ _ _ _ _)))

  -- the action of T on hom-categories
  TFun : Functor (FUNCTOR C D)
                 (FUNCTOR (|FreeMonoidalOn| C) (|FreeMonoidalOn| D))
  TFun .F-ob = T₁
  TFun .F-hom {x = F₁} {y = G₁} = T₂ F₁ G₁
  TFun .F-id {x = F₁} = T₂-id F₁
  TFun .F-seq β γ = T₂-seq _ _ _ β γ

-- The multiplication: FreeMonoidalOn C is already monoidal, so the
-- identity extends to it.
module _ (C : Category ℓC ℓC') where
  μFreeStr : StrongMonoidalFunctor
    (FreeMonoidalOn (|FreeMonoidalOn| C)) (FreeMonoidalOn C)
  μFreeStr = rec (|FreeMonoidalOn| C) (FreeMonoidalOn C) Id

  μFree : Functor (|FreeMonoidalOn| (|FreeMonoidalOn| C)) (|FreeMonoidalOn| C)
  μFree = μFreeStr .StrongMonoidalFunctor.F

-- The monad laws, as natural isomorphisms of the underlying functors.
module _ (C : Category ℓC ℓC') where
  private
    TC = |FreeMonoidalOn| C
    T²C = |FreeMonoidalOn| TC
    FC = FreeMonoidalOn C
    module FC = MonoidalCategory FC

  μ-ηR : μFree C ∘F ηFree TC ≡ Id
  μ-ηR = Functor≡ (λ _ → refl) (λ _ → refl)

  μ-ηL : (μFree C ∘F T₁ (ηFree C)) ≅ᶜ Id
  μ-ηL = uniq C FC (recSeqStr FC (ηFree TC ∘F ηFree C) Id) IdStr ı≅ where
    ı≅ : ((μFree C ∘F T₁ (ηFree C)) ∘F ηFree C) ≅ᶜ (Id ∘F ηFree C)
    ı≅ .trans .N-ob x = FC.id
    ı≅ .trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd

  μ-assoc : (μFree C ∘F T₁ (μFree C)) ≅ᶜ (μFree C ∘F μFree TC)
  μ-assoc = uniq T²C FC
    (recSeqStr FC (ηFree TC ∘F μFree C) Id) (recSeqStr FC Id Id) ı≅ where
    ı≅ : ((μFree C ∘F T₁ (μFree C)) ∘F ηFree T²C)
       ≅ᶜ ((μFree C ∘F μFree TC) ∘F ηFree T²C)
    ı≅ .trans .N-ob x = FC.id
    ı≅ .trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd

-- Naturality of η (strict) and of μ (up to natural isomorphism).
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} (F : Functor C D) where
  private
    TC = |FreeMonoidalOn| C
    TD = |FreeMonoidalOn| D
    FD = FreeMonoidalOn D
    module FD = MonoidalCategory FD

  ηFree-nat : T₁ F ∘F ηFree C ≡ ηFree D ∘F F
  ηFree-nat = rec-β C FD (ηFree D ∘F F)

  μFree-nat : (μFree D ∘F T₁ (T₁ F)) ≅ᶜ (T₁ F ∘F μFree C)
  μFree-nat = uniq TC FD
    (recSeqStr FD (ηFree TD ∘F T₁ F) Id)
    (recSeqStr FD Id (ηFree D ∘F F)) ı≅ where
    ı≅ : ((μFree D ∘F T₁ (T₁ F)) ∘F ηFree TC)
       ≅ᶜ ((T₁ F ∘F μFree C) ∘F ηFree TC)
    ı≅ .trans .N-ob x = FD.id
    ı≅ .trans .N-hom f = FD.⋆IdR _ ∙ sym (FD.⋆IdL _)
    ı≅ .nIso x = idCatIso .snd
