{- Free cartesian category generated by a category -}
{-# OPTIONS --lossy-unification #-}
module Cubical.Categories.Instances.Free.CartesianCategory.OnCategory where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv
open import Cubical.Foundations.Function
open import Cubical.Foundations.Isomorphism
open import Cubical.Foundations.HLevels
open import Cubical.Foundations.Equiv.Dependent
open import Cubical.Data.Sigma hiding (_×_)
open import Cubical.Data.Sigma using () renaming (_×_ to _×ₜ_)
open import Cubical.Data.Unit

open import Cubical.Categories.Category.Base
open import Cubical.Categories.Functor
open import Cubical.Categories.NaturalTransformation
open import Cubical.Categories.Isomorphism
open import Cubical.Categories.Limits.Cartesian.Base
open import Cubical.Categories.Limits.Terminal.More
open import Cubical.Categories.Limits.BinProduct.More
open import Cubical.Categories.Presheaf.Representable
open import Cubical.Categories.Presheaf.Representable.More
open import Cubical.Categories.Presheaf.Constructions.Reindex
open import Cubical.Categories.Presheaf.Constructions.Unit
open import Cubical.Categories.Presheaf.Morphism.Alt
import Cubical.Data.Equality as Eq

open import Cubical.Categories.Displayed.Base
open import Cubical.Categories.Displayed.More
open import Cubical.Categories.Displayed.HLevels
open import Cubical.Categories.Displayed.HLevels.PropValuedPresheaf
open import Cubical.Categories.Displayed.Limits.CartesianV'
open import Cubical.Categories.Displayed.Section.Base
open import Cubical.Categories.Displayed.Presheaf.Uncurried.Base
open import Cubical.Categories.Displayed.Presheaf.Uncurried.Constructions
open import Cubical.Categories.Displayed.Presheaf.Uncurried.UniversalProperties
open import Cubical.Categories.Presheaf.Base
open import Cubical.Categories.Instances.Fiber
open import Cubical.Categories.Instances.BinProduct
open import Cubical.Categories.Instances.Functors
open import Cubical.Categories.Bicategory.Instances.CAT.Structured.Terminal
open import Cubical.Categories.Bicategory.Instances.CAT.Structured.Cartesian
open import Cubical.Categories.Displayed.Instances.Arrow.Base
open import Cubical.Categories.Displayed.Instances.Reindex.Base
open import Cubical.Categories.Displayed.Instances.Reindex.Properties
open import Cubical.Categories.Displayed.Presheaf.Uncurried.Representable
open import Cubical.Categories.Displayed.Instances.Weaken.Base as Wk
open import Cubical.Categories.Displayed.Instances.Weaken.UncurriedProperties

private
  variable
    ℓC ℓC' ℓD ℓD' ℓE ℓE' ℓCᴰ ℓCᴰ' : Level

open Category
open Functor
open Section
open NatTrans
open CartesianCategory renaming (C to Cat) using (term; bp)
open UniversalElement

module _ (C : Category ℓC ℓC') where
  private module C = Category C

  data CartOb : Type ℓC where
    ↑ : C .ob → CartOb
    _×_ : CartOb → CartOb → CartOb
    ⊤ : CartOb

  data Exp : CartOb → CartOb → Type (ℓ-max ℓC ℓC') where
    idₑ : ∀ {Γ} → Exp Γ Γ
    _⋆ₑ_ : ∀ {Γ Γ' Γ''} → Exp Γ Γ' → Exp Γ' Γ'' → Exp Γ Γ''
    ⋆ₑIdL : ∀ {Γ Δ} (δ : Exp Γ Δ) → idₑ ⋆ₑ δ ≡ δ
    ⋆ₑIdR : ∀ {Γ Δ} (δ : Exp Γ Δ) → δ ⋆ₑ idₑ ≡ δ
    ⋆ₑAssoc : ∀ {Γ Γ' Γ'' Γ'''}
      (δ : Exp Γ Γ')(δ' : Exp Γ' Γ'')(δ'' : Exp Γ'' Γ''')
      → (δ ⋆ₑ δ') ⋆ₑ δ'' ≡ δ ⋆ₑ (δ' ⋆ₑ δ'')
    isSetExp : ∀ {Γ Γ'} → isSet (Exp Γ Γ')

    ↑ₘ : ∀ {x y} → C [ x , y ] → Exp (↑ x) (↑ y)
    ↑ₘId : ∀ {x} → ↑ₘ (C .id {x}) ≡ idₑ
    ↑ₘSeq : ∀ {x y z} (f : C [ x , y ])(g : C [ y , z ])
          → ↑ₘ (f ⋆⟨ C ⟩ g) ≡ ↑ₘ f ⋆ₑ ↑ₘ g

    !ₑ : ∀ {Γ} → Exp Γ ⊤
    ⊤η : ∀ {Γ} (t : Exp Γ ⊤) → t ≡ !ₑ
    π₁ : ∀ {Γ Δ} → Exp (Γ × Δ) Γ
    π₂ : ∀ {Γ Δ} → Exp (Γ × Δ) Δ
    ⟨_,_⟩ : ∀ {Γ Δ Δ'} → Exp Γ Δ → Exp Γ Δ' → Exp Γ (Δ × Δ')
    ×β₁ : ∀ {Γ Δ Δ'}{t : Exp Γ Δ}{t' : Exp Γ Δ'} → ⟨ t , t' ⟩ ⋆ₑ π₁ ≡ t
    ×β₂ : ∀ {Γ Δ Δ'}{t : Exp Γ Δ}{t' : Exp Γ Δ'} → ⟨ t , t' ⟩ ⋆ₑ π₂ ≡ t'
    ×η : ∀ {Γ Δ Δ'}{t : Exp Γ (Δ × Δ')} → t ≡ ⟨ t ⋆ₑ π₁ , t ⋆ₑ π₂ ⟩

  |FreeCartesianOn| : Category ℓC (ℓ-max ℓC ℓC')
  |FreeCartesianOn| .ob = CartOb
  |FreeCartesianOn| .Hom[_,_] = Exp
  |FreeCartesianOn| .id = idₑ
  |FreeCartesianOn| ._⋆_ = _⋆ₑ_
  |FreeCartesianOn| .⋆IdL = ⋆ₑIdL
  |FreeCartesianOn| .⋆IdR = ⋆ₑIdR
  |FreeCartesianOn| .⋆Assoc = ⋆ₑAssoc
  |FreeCartesianOn| .isSetHom = isSetExp

  FreeCartesianOn : CartesianCategory ℓC (ℓ-max ℓC ℓC')
  FreeCartesianOn .Cat = |FreeCartesianOn|
  FreeCartesianOn .term .vertex = ⊤
  FreeCartesianOn .term .element = tt
  FreeCartesianOn .term .universal _ =
    isIsoToIsEquiv ((λ _ → !ₑ) , ((λ _ → refl) , λ _ → sym $ ⊤η _))
  FreeCartesianOn .bp (Γ , Δ) .vertex = Γ × Δ
  FreeCartesianOn .bp (Γ , Δ) .element = π₁ , π₂
  FreeCartesianOn .bp (Γ , Δ) .universal Θ = isIsoToIsEquiv
    ( (λ z → ⟨ z .fst , z .snd ⟩)
    , (λ _ → ΣPathP (×β₁ , ×β₂))
    , (λ _ → sym $ ×η))

  ηFree : Functor C |FreeCartesianOn|
  ηFree .F-ob = ↑
  ηFree .F-hom = ↑ₘ
  ηFree .F-id = ↑ₘId
  ηFree .F-seq = ↑ₘSeq

  -- Elimination: a section of a displayed cartesian category over
  -- FreeCartesianOn along ηFree extends to a global section.
  module _ (CCᴰ : CartesianCategoryᴰ FreeCartesianOn ℓCᴰ ℓCᴰ') where
    open CartesianCategoryᴰ CCᴰ
    open UniversalElementᴰNotation
    module _ (ı : Section ηFree Cᴰ) where
      private module ı = Section ı

      elim-ob : ∀ A → Cᴰ.ob[ A ]
      elim-ob (↑ x) = ı.F-obᴰ x
      elim-ob (A × B) = bpᴰ (elim-ob A) (elim-ob B) .fst
      elim-ob ⊤ = termᴰ .fst

      elim-hom : ∀ {A B} (f : |FreeCartesianOn| [ A , B ])
        → Cᴰ [ f ][ elim-ob A , elim-ob B ]
      elim-hom idₑ = Cᴰ.idᴰ
      elim-hom (f ⋆ₑ g) = elim-hom f Cᴰ.⋆ᴰ elim-hom g
      elim-hom (⋆ₑIdL f i) = Cᴰ.⋆IdLᴰ (elim-hom f) i
      elim-hom (⋆ₑIdR f i) = Cᴰ.⋆IdRᴰ (elim-hom f) i
      elim-hom (⋆ₑAssoc f g h i) =
        Cᴰ.⋆Assocᴰ (elim-hom f) (elim-hom g) (elim-hom h) i
      elim-hom (isSetExp f g p q i j) =
        isSetHomᴰ' Cᴰ (elim-hom f) (elim-hom g)
          (cong elim-hom p) (cong elim-hom q) i j
      elim-hom (↑ₘ f) = ı.F-homᴰ f
      elim-hom (↑ₘId i) = ı.F-idᴰ i
      elim-hom (↑ₘSeq f g i) = ı.F-seqᴰ f g i
      elim-hom !ₑ = termᴰ.introᴰ tt
      elim-hom (⊤η f i) = Cᴰ.rectify {e' = ⊤η f} (termᴰ.ηᴰ (elim-hom f)) i
      elim-hom π₁ = bpᴰ.πᴰ₁
      elim-hom π₂ = bpᴰ.πᴰ₂
      elim-hom ⟨ f , g ⟩ = bpᴰ.introᴰ (elim-hom f , elim-hom g)
      elim-hom (×β₁ {t = f}{t' = g} i) =
        Cᴰ.rectify {e' = ×β₁} (bpᴰ.×βᴰ₁ (elim-hom f) (elim-hom g)) i
      elim-hom (×β₂ {t = f}{t' = g} i) =
        Cᴰ.rectify {e' = ×β₂} (bpᴰ.×βᴰ₂ (elim-hom f) (elim-hom g)) i
      elim-hom (×η {t = f} i) =
        Cᴰ.rectify {e' = ×η} (bpᴰ.×ηᴰ (elim-hom f)) i

      elim : GlobalSection Cᴰ
      elim .F-obᴰ = elim-ob
      elim .F-homᴰ = elim-hom
      elim .F-idᴰ = refl
      elim .F-seqᴰ _ _ = refl

  -- Universal property: restriction along ηFree from product
  -- preserving functors into CC to functors into CC.C has a section.
  module _ (CC : CartesianCategory ℓD ℓD') where
    private
      module CC = CartesianCategory CC
      wkCC = weakenCartesianCategory FreeCartesianOn CC
    module _ (G : Functor C CC.C) where
      rec : Functor |FreeCartesianOn| CC.C
      rec = Wk.introS⁻ (elim wkCC (Wk.introS ηFree G))

      rec-β : rec ∘F ηFree ≡ G
      rec-β = Functor≡ (λ _ → refl) (λ _ → refl)

      rec-preservesBinProducts :
        preservesProvidedBinProducts rec (FreeCartesianOn .bp)
      rec-preservesBinProducts A B =
        strictlyPreservesUniversalElement (preservesBinProdCones rec A B)
          (FreeCartesianOn .bp (A , B)) (CC.bp _) Eq.refl refl

      rec-preservesTerminal : preservesTerminal' rec (FreeCartesianOn .term)
      rec-preservesTerminal =
        strictlyPreservesUniversalElement
          (invPshIso (reindPsh-Unit rec) .PshIso.trans)
          (FreeCartesianOn .term) CC.term Eq.refl refl

      recCF : CartesianFunctor FreeCartesianOn CC.C
      recCF = rec , rec-preservesBinProducts

  {- Two dimensional uniqueness.  There is no separate notion of
     "cartesian natural transformation": naturality at π₁, π₂ already
     says σ commutes with the product comparisons.  What must be
     assumed instead is that the codomain functor preserves the finite
     products, so that maps into Q ⊤ and Q (A × B) are determined. -}
  preservesTerminalOn : {D : Category ℓD ℓD'}
    → Functor |FreeCartesianOn| D → Type _
  preservesTerminalOn Q = preservesTerminal' Q (FreeCartesianOn .term)

  preservesBinProductsOn : {D : Category ℓD ℓD'}
    → Functor |FreeCartesianOn| D → Type _
  preservesBinProductsOn Q =
    preservesProvidedBinProducts Q (FreeCartesianOn .bp)

  module TwoDim {D : Category ℓD ℓD'} (P Q : Functor |FreeCartesianOn| D)
    (Q-1 : preservesTerminalOn Q) (Q-× : preservesBinProductsOn Q) where
    private
      module D = Category D
      module Q⊤ = UniversalElementNotation
        (isUniversal→UniversalElement UnitPsh Q-1)
      module Q× {A B} = UniversalElementNotation
        (isUniversal→UniversalElement _ (Q-× A B))

      Aᴰ : Categoryᴰ |FreeCartesianOn| ℓD' ℓD'
      Aᴰ = reindex (Arrow D) (P ,F Q)

      hasPropHomsAᴰ : hasPropHoms Aᴰ
      hasPropHomsAᴰ f = hasPropHomsArrow D _

      motive : CartesianCategoryᴰ FreeCartesianOn ℓD' ℓD'
      motive .CartesianCategoryᴰ.Cᴰ = Aᴰ
      motive .CartesianCategoryᴰ.termᴰ =
        mkPropHomsUEᴰ Aᴰ hasPropHomsAᴰ UnitPsh UnitPshᴰ
          (λ _ → isPropUnit) (FreeCartesianOn .term)
          {vᴰ = Q⊤.intro {P ⟅ ⊤ ⟆} tt} tt
          (λ _ _ → Q⊤.extensionality refl)
      motive .CartesianCategoryᴰ.bpᴰ {A}{B} aᴰ bᴰ =
        mkPropHomsUEᴰ Aᴰ hasPropHomsAᴰ _
          (BinProductᴰSpec Aᴰ (FreeCartesianOn .bp (A , B)) aᴰ bᴰ)
          (λ Γᴰ → isProp× (hasPropHomsAᴰ _ Γᴰ _) (hasPropHomsAᴰ _ Γᴰ _))
          (FreeCartesianOn .bp (A , B)) {vᴰ = v} (πsq₁ , πsq₂) introsq
        where
        v : D [ P ⟅ A × B ⟆ , Q ⟅ A × B ⟆ ]
        v = Q×.intro (P ⟪ π₁ ⟫ D.⋆ aᴰ , P ⟪ π₂ ⟫ D.⋆ bᴰ)

        πsq₁ : P ⟪ π₁ ⟫ D.⋆ aᴰ ≡ v D.⋆ Q ⟪ π₁ ⟫
        πsq₁ = sym (cong fst Q×.β)

        πsq₂ : P ⟪ π₂ ⟫ D.⋆ bᴰ ≡ v D.⋆ Q ⟪ π₂ ⟫
        πsq₂ = sym (cong snd Q×.β)

        introsq : ∀ {Γ}{Γᴰ : D [ P ⟅ Γ ⟆ , Q ⟅ Γ ⟆ ]}
          (p : Exp Γ A ×ₜ Exp Γ B)
          → (P ⟪ p .fst ⟫ D.⋆ aᴰ ≡ Γᴰ D.⋆ Q ⟪ p .fst ⟫)
          ×ₜ (P ⟪ p .snd ⟫ D.⋆ bᴰ ≡ Γᴰ D.⋆ Q ⟪ p .snd ⟫)
          → P ⟪ ⟨ p .fst , p .snd ⟩ ⟫ D.⋆ v
            ≡ Γᴰ D.⋆ Q ⟪ ⟨ p .fst , p .snd ⟩ ⟫
        introsq (f , g) (sq₁ , sq₂) = Q×.extensionality (ΣPathP
          ( D.⋆Assoc _ _ _
            ∙ D.⟨ refl ⟩⋆⟨ sym πsq₁ ⟩
            ∙ sym (D.⋆Assoc _ _ _)
            ∙ D.⟨ sym (P .F-seq _ _) ∙ cong (P .F-hom) ×β₁ ⟩⋆⟨ refl ⟩
            ∙ sq₁
            ∙ D.⟨ refl ⟩⋆⟨ cong (Q .F-hom) (sym ×β₁) ∙ Q .F-seq _ _ ⟩
            ∙ sym (D.⋆Assoc _ _ _)
          , D.⋆Assoc _ _ _
            ∙ D.⟨ refl ⟩⋆⟨ sym πsq₂ ⟩
            ∙ sym (D.⋆Assoc _ _ _)
            ∙ D.⟨ sym (P .F-seq _ _) ∙ cong (P .F-hom) ×β₂ ⟩⋆⟨ refl ⟩
            ∙ sq₂
            ∙ D.⟨ refl ⟩⋆⟨ cong (Q .F-hom) (sym ×β₂) ∙ Q .F-seq _ _ ⟩
            ∙ sym (D.⋆Assoc _ _ _)))

    -- Every transformation between the restrictions extends.
    rec₂ : NatTrans (P ∘F ηFree) (Q ∘F ηFree) → NatTrans P Q
    rec₂ β = ArrowReflection (GlobalSectionReindex→Section _ _
      (elim motive S))
      where
        S : Section ηFree Aᴰ
        S = mkPropHomsSection hasPropHomsAᴰ (β .N-ob) (β .N-hom)

    rec₂-β : (β : NatTrans (P ∘F ηFree) (Q ∘F ηFree))
      → ∀ c → rec₂ β .N-ob (↑ c) ≡ β .N-ob c
    rec₂-β β c = refl

    uniq₂ : (σ τ : NatTrans P Q)
      → (∀ c → σ .N-ob (↑ c) ≡ τ .N-ob (↑ c))
      → σ ≡ τ
    uniq₂ σ τ p↑ = makeNatTransPath (funExt go) where
      go : ∀ A → σ .N-ob A ≡ τ .N-ob A
      go (↑ c) = p↑ c
      go ⊤ = Q⊤.extensionality refl
      go (A × B) = Q×.extensionality (ΣPathP
        ( sym (σ .N-hom π₁) ∙ cong (D._⋆_ (P ⟪ π₁ ⟫)) (go A)
          ∙ τ .N-hom π₁
        , sym (σ .N-hom π₂) ∙ cong (D._⋆_ (P ⟪ π₂ ⟫)) (go B)
          ∙ τ .N-hom π₂))

  {- One dimensional uniqueness: two functors out of the free
     cartesian category preserving the finite products that agree on
     the generators are naturally isomorphic. -}
  module _ {D : Category ℓD ℓD'} (P Q : Functor |FreeCartesianOn| D)
    (P-1 : preservesTerminalOn P) (P-× : preservesBinProductsOn P)
    (Q-1 : preservesTerminalOn Q) (Q-× : preservesBinProductsOn Q) where
    private
      module PQ = TwoDim P Q Q-1 Q-×
      module QP = TwoDim Q P P-1 P-×
      module PP = TwoDim P P P-1 P-×
      module QQ = TwoDim Q Q Q-1 Q-×
      module D = Category D

    uniq : NatIso (P ∘F ηFree) (Q ∘F ηFree) → NatIso P Q
    uniq ı .NatIso.trans = σ where
      σ = PQ.rec₂ (ı .NatIso.trans)
    uniq ı .NatIso.nIso A = isiso (τ .N-ob A)
      (λ i → τσ i .N-ob A) (λ i → στ i .N-ob A)
      where
      σ = PQ.rec₂ (ı .NatIso.trans)
      τ = QP.rec₂ (symNatIso ı .NatIso.trans)
      στ : seqTrans σ τ ≡ idTrans P
      στ = PP.uniq₂ _ _ (λ c → ı .NatIso.nIso c .isIso.ret)
      τσ : seqTrans τ σ ≡ idTrans Q
      τσ = QQ.uniq₂ _ _ (λ c → ı .NatIso.nIso c .isIso.sec)

-- Functoriality: T₁ F is the recursive extension of ↑ ∘ F.
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} (F : Functor C D) where
  T₁ : Functor (|FreeCartesianOn| C) (|FreeCartesianOn| D)
  T₁ = rec C (FreeCartesianOn D) (ηFree D ∘F F)

  T₁-1 : preservesTerminalOn C T₁
  T₁-1 = rec-preservesTerminal C (FreeCartesianOn D) (ηFree D ∘F F)

  T₁-× : preservesBinProductsOn C T₁
  T₁-× = rec-preservesBinProducts C (FreeCartesianOn D) (ηFree D ∘F F)

{- A composite of two rec-generated functors preserves the finite
   products on the nose, just as a single rec does. -}
module _ {A : Category ℓC ℓC'} {B : Category ℓD ℓD'}
         (CC : CartesianCategory ℓE ℓE')
         (G₁ : Functor A (|FreeCartesianOn| B))
         (G₂ : Functor B (CC .Cat)) where
  recSeq : Functor (|FreeCartesianOn| A) (CC .Cat)
  recSeq = rec B CC G₂ ∘F rec A (FreeCartesianOn B) G₁

  recSeq-1 : preservesTerminalOn A recSeq
  recSeq-1 = strictlyPreservesUniversalElement
    (invPshIso (reindPsh-Unit recSeq) .PshIso.trans)
    (FreeCartesianOn A .term) (CC .term) Eq.refl refl

  recSeq-× : preservesBinProductsOn A recSeq
  recSeq-× X Y = strictlyPreservesUniversalElement
    (preservesBinProdCones recSeq X Y)
    (FreeCartesianOn A .bp (X , Y)) (CC .bp _) Eq.refl refl

module _ {C : Category ℓC ℓC'} where
  private
    FC = FreeCartesianOn C
    module FC = Category (|FreeCartesianOn| C)

  T₁-id : NatIso (T₁ (Id {C = C})) Id
  T₁-id = uniq C (T₁ Id) Id (T₁-1 Id) (T₁-× Id)
    (idPreservesTerminal' (FC .term))
    (idPreservesBinProducts (FC .bp)) ı≅ where
    ı≅ : NatIso (T₁ (Id {C = C}) ∘F ηFree C) (Id ∘F ηFree C)
    ı≅ .NatIso.trans .N-ob x = FC.id
    ı≅ .NatIso.trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .NatIso.nIso x = idCatIso .snd

module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} {E : Category ℓE ℓE'}
         (F : Functor C D) (G : Functor D E) where
  private
    FE = FreeCartesianOn E
    module FE = Category (|FreeCartesianOn| E)

  T₁-seq : NatIso (T₁ (G ∘F F)) (T₁ G ∘F T₁ F)
  T₁-seq = uniq C (T₁ (G ∘F F)) (T₁ G ∘F T₁ F)
    (T₁-1 (G ∘F F)) (T₁-× (G ∘F F))
    (recSeq-1 FE (ηFree D ∘F F) (ηFree E ∘F G))
    (recSeq-× FE (ηFree D ∘F F) (ηFree E ∘F G)) ı≅ where
    ı≅ : NatIso (T₁ (G ∘F F) ∘F ηFree C) ((T₁ G ∘F T₁ F) ∘F ηFree C)
    ı≅ .NatIso.trans .N-ob x = FE.id
    ı≅ .NatIso.trans .N-hom f = FE.⋆IdR _ ∙ sym (FE.⋆IdL _)
    ı≅ .NatIso.nIso x = idCatIso .snd

-- The action of T on 2-cells, by two dimensional recursion.
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} (F G : Functor C D) where
  private
    module TD = TwoDim C (T₁ F) (T₁ G) (T₁-1 G) (T₁-× G)

  T₂ : NatTrans F G → NatTrans (T₁ F) (T₁ G)
  T₂ β = TD.rec₂ (natTrans (λ c → ↑ₘ (β .N-ob c))
    (λ f → sym (↑ₘSeq _ _) ∙ cong ↑ₘ (β .N-hom f) ∙ ↑ₘSeq _ _))

  T₂-β : (β : NatTrans F G) → ∀ c → T₂ β .N-ob (↑ c) ≡ ↑ₘ (β .N-ob c)
  T₂-β β c = refl

  -- Any transformation agreeing with T₂ β on the generators is T₂ β.
  T₂-uniq : (β : NatTrans F G) (σ : NatTrans (T₁ F) (T₁ G))
    → (∀ c → σ .N-ob (↑ c) ≡ ↑ₘ (β .N-ob c))
    → σ ≡ T₂ β
  T₂-uniq β σ p = TD.uniq₂ σ (T₂ β) p

module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} where
  T₂-id : (F : Functor C D) → T₂ F F (idTrans F) ≡ idTrans (T₁ F)
  T₂-id F = sym (T₂-uniq F F (idTrans F) (idTrans (T₁ F)) (λ c → sym ↑ₘId))

  T₂-seq : (F G H : Functor C D)
    (β : NatTrans F G) (γ : NatTrans G H)
    → T₂ F H (seqTrans β γ) ≡ seqTrans (T₂ F G β) (T₂ G H γ)
  T₂-seq F G H β γ = sym (T₂-uniq F H (seqTrans β γ)
    (seqTrans (T₂ F G β) (T₂ G H γ)) (λ c → sym (↑ₘSeq _ _)))

  -- the action of T on hom-categories
  TFun : Functor (FUNCTOR C D)
                 (FUNCTOR (|FreeCartesianOn| C) (|FreeCartesianOn| D))
  TFun .F-ob = T₁
  TFun .F-hom {x = F} {y = G} = T₂ F G
  TFun .F-id {x = F} = T₂-id F
  TFun .F-seq β γ = T₂-seq _ _ _ β γ

-- The multiplication: |FreeCartesianOn| C is already cartesian, so
-- the identity extends to it.
module _ (C : Category ℓC ℓC') where
  μFree : Functor (|FreeCartesianOn| (|FreeCartesianOn| C))
                  (|FreeCartesianOn| C)
  μFree = rec (|FreeCartesianOn| C) (FreeCartesianOn C) Id

  μFree-1 : preservesTerminalOn (|FreeCartesianOn| C) μFree
  μFree-1 = rec-preservesTerminal (|FreeCartesianOn| C)
    (FreeCartesianOn C) Id

  μFree-× : preservesBinProductsOn (|FreeCartesianOn| C) μFree
  μFree-× = rec-preservesBinProducts (|FreeCartesianOn| C)
    (FreeCartesianOn C) Id

-- The monad laws, as natural isomorphisms of the underlying functors.
module _ (C : Category ℓC ℓC') where
  private
    TC = |FreeCartesianOn| C
    T²C = |FreeCartesianOn| TC
    FC = FreeCartesianOn C
    module FC = Category TC

  μ-ηR : μFree C ∘F ηFree TC ≡ Id
  μ-ηR = rec-β TC FC Id

  μ-ηL : NatIso (μFree C ∘F T₁ (ηFree C)) Id
  μ-ηL = uniq C (μFree C ∘F T₁ (ηFree C)) Id
    (recSeq-1 FC (ηFree TC ∘F ηFree C) Id)
    (recSeq-× FC (ηFree TC ∘F ηFree C) Id)
    (idPreservesTerminal' (FC .term))
    (idPreservesBinProducts (FC .bp)) ı≅ where
    ı≅ : NatIso ((μFree C ∘F T₁ (ηFree C)) ∘F ηFree C) (Id ∘F ηFree C)
    ı≅ .NatIso.trans .N-ob x = FC.id
    ı≅ .NatIso.trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .NatIso.nIso x = idCatIso .snd

  μ-assoc : NatIso (μFree C ∘F T₁ (μFree C)) (μFree C ∘F μFree TC)
  μ-assoc = uniq T²C (μFree C ∘F T₁ (μFree C)) (μFree C ∘F μFree TC)
    (recSeq-1 FC (ηFree TC ∘F μFree C) Id)
    (recSeq-× FC (ηFree TC ∘F μFree C) Id)
    (recSeq-1 FC Id Id) (recSeq-× FC Id Id) ı≅ where
    ı≅ : NatIso ((μFree C ∘F T₁ (μFree C)) ∘F ηFree T²C)
                ((μFree C ∘F μFree TC) ∘F ηFree T²C)
    ı≅ .NatIso.trans .N-ob x = FC.id
    ı≅ .NatIso.trans .N-hom f = FC.⋆IdR _ ∙ sym (FC.⋆IdL _)
    ı≅ .NatIso.nIso x = idCatIso .snd

-- Naturality of η (strict) and of μ (up to natural isomorphism).
module _ {C : Category ℓC ℓC'} {D : Category ℓD ℓD'} (F : Functor C D) where
  private
    TC = |FreeCartesianOn| C
    TD = |FreeCartesianOn| D
    FD = FreeCartesianOn D
    module FD = Category TD

  ηFree-nat : T₁ F ∘F ηFree C ≡ ηFree D ∘F F
  ηFree-nat = rec-β C FD (ηFree D ∘F F)

  μFree-nat : NatIso (μFree D ∘F T₁ (T₁ F)) (T₁ F ∘F μFree C)
  μFree-nat = uniq TC (μFree D ∘F T₁ (T₁ F)) (T₁ F ∘F μFree C)
    (recSeq-1 FD (ηFree TD ∘F T₁ F) Id)
    (recSeq-× FD (ηFree TD ∘F T₁ F) Id)
    (recSeq-1 FD Id (ηFree D ∘F F))
    (recSeq-× FD Id (ηFree D ∘F F)) ı≅ where
    ı≅ : NatIso ((μFree D ∘F T₁ (T₁ F)) ∘F ηFree TC)
                ((T₁ F ∘F μFree C) ∘F ηFree TC)
    ı≅ .NatIso.trans .N-ob x = FD.id
    ı≅ .NatIso.trans .N-hom f = FD.⋆IdR _ ∙ sym (FD.⋆IdL _)
    ı≅ .NatIso.nIso x = idCatIso .snd
