{- Free biclosed monoidal category generated by a category -}
{-# OPTIONS --lossy-unification #-}
module Cubical.Categories.Instances.Free.MonoidalBiclosed.OnCategory where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv
open import Cubical.Foundations.Function
open import Cubical.Foundations.Equiv.Dependent
open import Cubical.Foundations.Isomorphism
open import Cubical.Data.Sigma

open import Cubical.Categories.Category.Base
open import Cubical.Categories.Isomorphism
open import Cubical.Categories.Monoidal.Base
open import Cubical.Categories.Monoidal.Biclosed
open import Cubical.Categories.Monoidal.Functor
open import Cubical.Categories.Adjoint.RightAdjoint
import Cubical.Categories.Instances.Free.Monoidal.OnCategory as FM
open import Cubical.Categories.Functor
open import Cubical.Categories.NaturalTransformation
open import Cubical.Categories.Presheaf.Representable
open import Cubical.Categories.Presheaf.Representable.More
open import Cubical.Categories.Presheaf.Constructions.Reindex
open import Cubical.Categories.Instances.Fiber

open import Cubical.Categories.Displayed.Base
open import Cubical.Categories.Displayed.Functor
open import Cubical.Categories.Displayed.Monoidal.Base
open import Cubical.Categories.Displayed.Instances.Sets.Base
open import Cubical.Categories.Displayed.Presheaf.Base
open import Cubical.Categories.Displayed.Presheaf.Representable
open import Cubical.Categories.Displayed.Presheaf.Constructions.ReindexFunctor.Base
open import Cubical.Categories.Displayed.HLevels
open import Cubical.Categories.Displayed.More
open import Cubical.Categories.Displayed.Section
open import Cubical.Categories.Displayed.NaturalTransformation
open import Cubical.Categories.Displayed.NaturalTransformation.More
open import Cubical.Categories.Displayed.Instances.Weaken.Monoidal
import Cubical.Categories.Displayed.Instances.Weaken.Base as Wk

private
  variable
    ℓC ℓC' ℓD ℓD' ℓE ℓE' : Level

open Category
open Functor
open NatTrans
open NatIso
open isIso
open UniversalElement
open StrongMonoidalFunctor
open StrongMonoidalStr
open LaxMonoidalStr
open Functorᴰ
open Section
open NatTransᴰ
open NatIsoᴰ
open isIsoᴰ
open UniversalElementᴰ

module _ (C : Category ℓC ℓC') where
  private module C = Category C

  data BiOb : Type ℓC where
    ↑ : C .ob → BiOb
    unit : BiOb
    _⊗_ : BiOb → BiOb → BiOb
    _⊸_ : BiOb → BiOb → BiOb
    _⟜_ : BiOb → BiOb → BiOb

  data BiMor : BiOb → BiOb → Type (ℓ-max ℓC ℓC') where
    idₑ : ∀ {x} → BiMor x x
    _⋆ₑ_ : ∀ {x y z} → BiMor x y → BiMor y z → BiMor x z
    ⋆ₑIdL : ∀ {x y} (e : BiMor x y) → idₑ ⋆ₑ e ≡ e
    ⋆ₑIdR : ∀ {x y} (e : BiMor x y) → e ⋆ₑ idₑ ≡ e
    ⋆ₑAssoc : ∀ {x y z D} (e : BiMor x y)(f : BiMor y z)(g : BiMor z D)
              → (e ⋆ₑ f) ⋆ₑ g ≡ e ⋆ₑ (f ⋆ₑ g)
    isSetHomₑ : ∀ {x y} → isSet (BiMor x y)

    ↑ₘ : ∀ {x y} → C [ x , y ] → BiMor (↑ x) (↑ y)
    ↑ₘId : ∀ {x} → ↑ₘ (C .id {x}) ≡ idₑ
    ↑ₘSeq : ∀ {x y z} (f : C [ x , y ]) (g : C [ y , z ])
          → ↑ₘ (f ⋆⟨ C ⟩ g) ≡ ↑ₘ f ⋆ₑ ↑ₘ g

    _⊗_ : ∀ {x x' y y'} → BiMor x y → BiMor x' y' → BiMor (x ⊗ x') (y ⊗ y')
    ⊗id : ∀ {x y} → idₑ ⊗ idₑ ≡ idₑ {x ⊗ y}
    ⊗⋆  : ∀ {x x' y y' z z'}
      (f : BiMor x y) (g : BiMor y z)
      (f' : BiMor x' y') (g' : BiMor y' z')
      → (f ⋆ₑ g) ⊗ (f' ⋆ₑ g') ≡ ((f ⊗ f') ⋆ₑ (g ⊗ g'))

    α : ∀ {x y z} → BiMor (x ⊗ (y ⊗ z)) ((x ⊗ y) ⊗ z)
    α⁻ : ∀ {x y z} → BiMor ((x ⊗ y) ⊗ z) (x ⊗ (y ⊗ z))
    α-nat : ∀ {x x' y y' z z'} →
      (f : BiMor x x')(g : BiMor y y')(h : BiMor z z')
      → ((f ⊗ (g ⊗ h)) ⋆ₑ α) ≡ (α ⋆ₑ ((f ⊗ g) ⊗ h))
    α⋆α⁻ : ∀ {x y z} → α {x}{y}{z} ⋆ₑ α⁻ ≡ idₑ
    α⁻⋆α : ∀ {x y z} → α⁻ {x}{y}{z} ⋆ₑ α ≡ idₑ

    η : ∀ {x} → BiMor (unit ⊗ x) x
    η⁻ : ∀ {x} → BiMor x (unit ⊗ x)
    η-nat : ∀ {x y} (f : BiMor x y) → ((idₑ ⊗ f) ⋆ₑ η) ≡ (η ⋆ₑ f)
    η⋆η⁻ : ∀ {x} → (η {x} ⋆ₑ η⁻) ≡ idₑ
    η⁻⋆η : ∀ {x} → (η⁻ {x} ⋆ₑ η) ≡ idₑ

    ρ : ∀ {x} → BiMor (x ⊗ unit) x
    ρ⁻ : ∀ {x} → BiMor x (x ⊗ unit)
    ρ-nat : ∀ {x y} (f : BiMor x y) → ((f ⊗ idₑ) ⋆ₑ ρ) ≡ (ρ ⋆ₑ f)
    ρ⋆ρ⁻ : ∀ {x} → (ρ {x} ⋆ₑ ρ⁻) ≡ idₑ
    ρ⁻⋆ρ : ∀ {x} → (ρ⁻ {x} ⋆ₑ ρ) ≡ idₑ

    pentagon : ∀ {w x y z} →
      (idₑ {w} ⊗ α {x}{y}{z}) ⋆ₑ (α ⋆ₑ (α ⊗ idₑ)) ≡ (α ⋆ₑ α)
    triangle : ∀ {x y} → α ⋆ₑ (ρ {x} ⊗ idₑ) ≡ (idₑ ⊗ (η {y}))

    lapp : ∀ {Δ Θ} → BiMor (Δ ⊗ (Δ ⊸ Θ)) Θ
    llam : ∀ {Δ Γ Θ} → BiMor (Δ ⊗ Γ) Θ → BiMor Γ (Δ ⊸ Θ)
    lβ : ∀ {Δ Γ Θ} (f : BiMor (Δ ⊗ Γ) Θ)
       → ((idₑ ⊗ llam f) ⋆ₑ lapp) ≡ f
    lη : ∀ {Δ Γ Θ} (g : BiMor Γ (Δ ⊸ Θ))
       → llam ((idₑ ⊗ g) ⋆ₑ lapp) ≡ g

    rapp : ∀ {Δ Θ} → BiMor ((Θ ⟜ Δ) ⊗ Δ) Θ
    rlam : ∀ {Δ Γ Θ} → BiMor (Γ ⊗ Δ) Θ → BiMor Γ (Θ ⟜ Δ)
    rβ : ∀ {Δ Γ Θ} (f : BiMor (Γ ⊗ Δ) Θ)
       → ((rlam f ⊗ idₑ) ⋆ₑ rapp) ≡ f
    rη : ∀ {Δ Γ Θ} (g : BiMor Γ (Θ ⟜ Δ))
       → rlam ((g ⊗ idₑ) ⋆ₑ rapp) ≡ g

  |FreeBiclosedOn| : Category ℓC (ℓ-max ℓC ℓC')
  |FreeBiclosedOn| .ob = BiOb
  |FreeBiclosedOn| .Hom[_,_] = BiMor
  |FreeBiclosedOn| .id = idₑ
  |FreeBiclosedOn| ._⋆_ = _⋆ₑ_
  |FreeBiclosedOn| .⋆IdL = ⋆ₑIdL
  |FreeBiclosedOn| .⋆IdR = ⋆ₑIdR
  |FreeBiclosedOn| .⋆Assoc = ⋆ₑAssoc
  |FreeBiclosedOn| .isSetHom = isSetHomₑ

  FreeBiclosedOnTenStr : TensorStr |FreeBiclosedOn|
  FreeBiclosedOnTenStr .TensorStr.─⊗─ .F-ob (x , y) = x ⊗ y
  FreeBiclosedOnTenStr .TensorStr.─⊗─ .F-hom (f , g) = f ⊗ g
  FreeBiclosedOnTenStr .TensorStr.─⊗─ .F-id = ⊗id
  FreeBiclosedOnTenStr .TensorStr.─⊗─ .F-seq f g =
    ⊗⋆ (f .fst) (g .fst) (f .snd) (g .snd)
  FreeBiclosedOnTenStr .TensorStr.unit = unit

  FreeBiclosedOnMonStr : MonoidalStr |FreeBiclosedOn|
  FreeBiclosedOnMonStr .MonoidalStr.tenstr = FreeBiclosedOnTenStr
  FreeBiclosedOnMonStr .MonoidalStr.α .trans .N-ob x = α
  FreeBiclosedOnMonStr .MonoidalStr.α .trans .N-hom f = α-nat _ _ _
  FreeBiclosedOnMonStr .MonoidalStr.α .nIso x .inv = α⁻
  FreeBiclosedOnMonStr .MonoidalStr.α .nIso x .sec = α⁻⋆α
  FreeBiclosedOnMonStr .MonoidalStr.α .nIso x .ret = α⋆α⁻
  FreeBiclosedOnMonStr .MonoidalStr.η .trans .N-ob x = η
  FreeBiclosedOnMonStr .MonoidalStr.η .trans .N-hom = η-nat
  FreeBiclosedOnMonStr .MonoidalStr.η .nIso x .inv = η⁻
  FreeBiclosedOnMonStr .MonoidalStr.η .nIso x .sec = η⁻⋆η
  FreeBiclosedOnMonStr .MonoidalStr.η .nIso x .ret = η⋆η⁻
  FreeBiclosedOnMonStr .MonoidalStr.ρ .trans .N-ob x = ρ
  FreeBiclosedOnMonStr .MonoidalStr.ρ .trans .N-hom = ρ-nat
  FreeBiclosedOnMonStr .MonoidalStr.ρ .nIso x .inv = ρ⁻
  FreeBiclosedOnMonStr .MonoidalStr.ρ .nIso x .sec = ρ⁻⋆ρ
  FreeBiclosedOnMonStr .MonoidalStr.ρ .nIso x .ret = ρ⋆ρ⁻
  FreeBiclosedOnMonStr .MonoidalStr.pentagon w x y z = pentagon
  FreeBiclosedOnMonStr .MonoidalStr.triangle x y = triangle

  FreeMonoidal : MonoidalCategory ℓC (ℓ-max ℓC ℓC')
  FreeMonoidal .MonoidalCategory.C = |FreeBiclosedOn|
  FreeMonoidal .MonoidalCategory.monstr = FreeBiclosedOnMonStr

  FreeLRes : ∀ Δ Θ → LeftResidual FreeBiclosedOnTenStr Δ Θ
  FreeLRes Δ Θ .vertex = Δ ⊸ Θ
  FreeLRes Δ Θ .element = lapp
  FreeLRes Δ Θ .universal Γ = isIsoToIsEquiv (llam , lβ , lη)

  FreeRRes : ∀ Δ Θ → RightResidual FreeBiclosedOnTenStr Δ Θ
  FreeRRes Δ Θ .vertex = Θ ⟜ Δ
  FreeRRes Δ Θ .element = rapp
  FreeRRes Δ Θ .universal Γ = isIsoToIsEquiv (rlam , rβ , rη)

  FreeBiclosedOn : BiclosedMonoidalCategory ℓC (ℓ-max ℓC ℓC')
  FreeBiclosedOn .BiclosedMonoidalCategory.C = |FreeBiclosedOn|
  FreeBiclosedOn .BiclosedMonoidalCategory.biclosedstr
    .BiclosedMonoidalStr.monstr = FreeBiclosedOnMonStr
  FreeBiclosedOn .BiclosedMonoidalCategory.biclosedstr
    .BiclosedMonoidalStr.lres = FreeLRes
  FreeBiclosedOn .BiclosedMonoidalCategory.biclosedstr
    .BiclosedMonoidalStr.rres = FreeRRes

  ηFree : Functor C |FreeBiclosedOn|
  ηFree .F-ob = ↑
  ηFree .F-hom = ↑ₘ
  ηFree .F-id = ↑ₘId
  ηFree .F-seq = ↑ₘSeq

{- Displayed biclosed monoidal categories.  The residual halves are
   displayed universal elements of the reindexed representables, i.e.
   displayed right adjoints; TODO: they belong in
   Displayed.Monoidal.Biclosed. -}
module _ {M : MonoidalCategory ℓD ℓD'} (Mᴰ : MonoidalCategoryᴰ M ℓE ℓE')
  where
  private
    module M = MonoidalCategory M
    module Mᴰ = MonoidalCategoryᴰ Mᴰ
    module Cᴰ = Fibers Mᴰ.Cᴰ

  A⊗ᴰ-F : ∀ {A} (Aᴰ : Mᴰ.ob[ A ]) → Functorᴰ (A⊗-F M.tenstr A) Mᴰ.Cᴰ Mᴰ.Cᴰ
  A⊗ᴰ-F Aᴰ .F-obᴰ Xᴰ = Aᴰ Mᴰ.⊗ᴰ Xᴰ
  A⊗ᴰ-F Aᴰ .F-homᴰ fᴰ = Mᴰ.idᴰ Mᴰ.⊗ₕᴰ fᴰ
  A⊗ᴰ-F Aᴰ .F-idᴰ = Mᴰ.─⊗ᴰ─ .F-idᴰ
  A⊗ᴰ-F Aᴰ .F-seqᴰ {f = f}{g = g} fᴰ gᴰ = Cᴰ.rectifyOut $
    (λ i → M.─⊗─ .F-hom (q i .fst , f M.⋆ g)
         , Mᴰ.─⊗ᴰ─ .F-homᴰ (q i .snd , fᴰ Mᴰ.⋆ᴰ gᴰ))
    ∙ Cᴰ.≡in (Mᴰ.─⊗ᴰ─ .F-seqᴰ (Mᴰ.idᴰ , fᴰ) (Mᴰ.idᴰ , gᴰ))
    where q = sym (Cᴰ.≡in (Mᴰ.⋆IdLᴰ Mᴰ.idᴰ))

  -⊗ᴰAF : ∀ {A} (Aᴰ : Mᴰ.ob[ A ]) → Functorᴰ (-⊗AF M.tenstr A) Mᴰ.Cᴰ Mᴰ.Cᴰ
  -⊗ᴰAF Aᴰ .F-obᴰ Xᴰ = Xᴰ Mᴰ.⊗ᴰ Aᴰ
  -⊗ᴰAF Aᴰ .F-homᴰ fᴰ = fᴰ Mᴰ.⊗ₕᴰ Mᴰ.idᴰ
  -⊗ᴰAF Aᴰ .F-idᴰ = Mᴰ.─⊗ᴰ─ .F-idᴰ
  -⊗ᴰAF Aᴰ .F-seqᴰ {f = f}{g = g} fᴰ gᴰ = Cᴰ.rectifyOut $
    (λ i → M.─⊗─ .F-hom (f M.⋆ g , q i .fst)
         , Mᴰ.─⊗ᴰ─ .F-homᴰ (fᴰ Mᴰ.⋆ᴰ gᴰ , q i .snd))
    ∙ Cᴰ.≡in (Mᴰ.─⊗ᴰ─ .F-seqᴰ (fᴰ , Mᴰ.idᴰ) (gᴰ , Mᴰ.idᴰ))
    where q = sym (Cᴰ.≡in (Mᴰ.⋆IdLᴰ Mᴰ.idᴰ))

  LeftResidualᴰ : ∀ {Δ Θ} (Δᴰ : Mᴰ.ob[ Δ ]) (Θᴰ : Mᴰ.ob[ Θ ])
    → LeftResidual M.tenstr Δ Θ → Type _
  LeftResidualᴰ Δᴰ Θᴰ lr = UniversalElementᴰ Mᴰ.Cᴰ lr
    (reindPshᴰFunctor (A⊗ᴰ-F Δᴰ) (Mᴰ.Cᴰ [-][-, Θᴰ ]))

  RightResidualᴰ : ∀ {Δ Θ} (Δᴰ : Mᴰ.ob[ Δ ]) (Θᴰ : Mᴰ.ob[ Θ ])
    → RightResidual M.tenstr Δ Θ → Type _
  RightResidualᴰ Δᴰ Θᴰ rr = UniversalElementᴰ Mᴰ.Cᴰ rr
    (reindPshᴰFunctor (-⊗ᴰAF Δᴰ) (Mᴰ.Cᴰ [-][-, Θᴰ ]))

BM→Mon : BiclosedMonoidalCategory ℓD ℓD' → MonoidalCategory ℓD ℓD'
BM→Mon B .MonoidalCategory.C = B .BiclosedMonoidalCategory.C
BM→Mon B .MonoidalCategory.monstr =
  B .BiclosedMonoidalCategory.biclosedstr .BiclosedMonoidalStr.monstr

record BiclosedMonoidalCategoryᴰ (B : BiclosedMonoidalCategory ℓD ℓD')
  (ℓE ℓE' : Level)
  : Type (ℓ-suc (ℓ-max (ℓ-max ℓD ℓD') (ℓ-max ℓE ℓE'))) where
  private module B = BiclosedMonoidalCategory B
  field
    Mᴰ : MonoidalCategoryᴰ (BM→Mon B) ℓE ℓE'
  open MonoidalCategoryᴰ Mᴰ public
  field
    lresᴰ : ∀ {Δ Θ} (Δᴰ : ob[ Δ ]) (Θᴰ : ob[ Θ ])
      → LeftResidualᴰ Mᴰ Δᴰ Θᴰ (B.lres Δ Θ)
    rresᴰ : ∀ {Δ Θ} (Δᴰ : ob[ Δ ]) (Θᴰ : ob[ Θ ])
      → RightResidualᴰ Mᴰ Δᴰ Θᴰ (B.rres Δ Θ)

open BiclosedMonoidalCategoryᴰ

{- The weakening of a biclosed monoidal category is biclosed
   displayed: the displayed presheaves are constant, so the universal
   property is the target's. -}
module _ (B : BiclosedMonoidalCategory ℓD ℓD')
         (N : BiclosedMonoidalCategory ℓE ℓE') where
  private
    module B = BiclosedMonoidalCategory B
    module N = BiclosedMonoidalCategory N
    module Nl (Δ Θ : N.C .ob) = UniversalElementNotation (N.lres Δ Θ)
    module Nr (Δ Θ : N.C .ob) = UniversalElementNotation (N.rres Δ Θ)

  weakenBiclosed : BiclosedMonoidalCategoryᴰ B ℓE ℓE'
  weakenBiclosed .Mᴰ = weaken (BM→Mon B) (BM→Mon N)
  weakenBiclosed .lresᴰ Δᴰ Θᴰ .vertexᴰ = Nl.vertex Δᴰ Θᴰ
  weakenBiclosed .lresᴰ Δᴰ Θᴰ .elementᴰ = Nl.element Δᴰ Θᴰ
  weakenBiclosed .lresᴰ Δᴰ Θᴰ .universalᴰ .isIsoOver.inv _ = Nl.intro Δᴰ Θᴰ
  weakenBiclosed .lresᴰ Δᴰ Θᴰ .universalᴰ .isIsoOver.rightInv _ _ =
    Nl.β Δᴰ Θᴰ
  weakenBiclosed .lresᴰ Δᴰ Θᴰ .universalᴰ .isIsoOver.leftInv _ _ =
    sym (Nl.η Δᴰ Θᴰ)
  weakenBiclosed .rresᴰ Δᴰ Θᴰ .vertexᴰ = Nr.vertex Δᴰ Θᴰ
  weakenBiclosed .rresᴰ Δᴰ Θᴰ .elementᴰ = Nr.element Δᴰ Θᴰ
  weakenBiclosed .rresᴰ Δᴰ Θᴰ .universalᴰ .isIsoOver.inv _ = Nr.intro Δᴰ Θᴰ
  weakenBiclosed .rresᴰ Δᴰ Θᴰ .universalᴰ .isIsoOver.rightInv _ _ =
    Nr.β Δᴰ Θᴰ
  weakenBiclosed .rresᴰ Δᴰ Θᴰ .universalᴰ .isIsoOver.leftInv _ _ =
    sym (Nr.η Δᴰ Θᴰ)

module _ (C : Category ℓC ℓC') where
  private module C = Category C

  -- Elimination: a section of a displayed biclosed monoidal category
  -- over FreeBiclosedOn along ηFree extends to a global section.
  module _ (Bᴰ : BiclosedMonoidalCategoryᴰ (FreeBiclosedOn C) ℓE ℓE') where
    private
      module Bᴰ = BiclosedMonoidalCategoryᴰ Bᴰ
      module Cᴰ = Fibers Bᴰ.Cᴰ
    module _ (ı : Section (ηFree C) Bᴰ.Cᴰ) where
      private module ı = Section ı

      elim-ob : ∀ x → Bᴰ.ob[ x ]
      elim-ob (↑ x) = ı.F-obᴰ x
      elim-ob unit = Bᴰ.unitᴰ
      elim-ob (x ⊗ y) = elim-ob x Bᴰ.⊗ᴰ elim-ob y
      elim-ob (x ⊸ y) = Bᴰ.lresᴰ (elim-ob x) (elim-ob y) .vertexᴰ
      elim-ob (x ⟜ y) = Bᴰ.rresᴰ (elim-ob y) (elim-ob x) .vertexᴰ

      elim-hom : ∀ {x y}(f : |FreeBiclosedOn| C [ x , y ])
        → Bᴰ.Hom[ f ][ elim-ob x , elim-ob y ]
      elim-hom idₑ = Bᴰ.idᴰ
      elim-hom (f ⋆ₑ g) = elim-hom f Bᴰ.⋆ᴰ elim-hom g
      elim-hom (⋆ₑIdL f i) = Bᴰ.⋆IdLᴰ (elim-hom f) i
      elim-hom (⋆ₑIdR f i) = Bᴰ.⋆IdRᴰ (elim-hom f) i
      elim-hom (⋆ₑAssoc f g h i) =
        Bᴰ.⋆Assocᴰ (elim-hom f)(elim-hom g)(elim-hom h) i
      elim-hom (isSetHomₑ f g p q i j) =
        isSetHomᴰ' Bᴰ.Cᴰ
          (elim-hom f) (elim-hom g)
          (cong elim-hom p) (cong elim-hom q)
          i j
      elim-hom (↑ₘ f) = ı.F-homᴰ f
      elim-hom (↑ₘId i) = ı.F-idᴰ i
      elim-hom (↑ₘSeq f g i) = ı.F-seqᴰ f g i
      elim-hom (f ⊗ g) = elim-hom f Bᴰ.⊗ₕᴰ elim-hom g
      elim-hom (⊗id i) = Bᴰ.─⊗ᴰ─ .F-idᴰ i
      elim-hom (⊗⋆ f g f' g' i) =
        Bᴰ.─⊗ᴰ─ .F-seqᴰ
          ((elim-hom f) , (elim-hom f'))
          (elim-hom g , elim-hom g')
          i
      elim-hom α = Bᴰ.αᴰ⟨ _ , _ , _ ⟩
      elim-hom (α-nat f g h i) =
        Bᴰ.αᴰ .transᴰ .N-homᴰ ((elim-hom f) , (elim-hom g) , (elim-hom h)) i
      elim-hom α⁻ = Bᴰ.αᴰ .nIsoᴰ _ .invᴰ
      elim-hom (α⋆α⁻ i) = Bᴰ.αᴰ .nIsoᴰ _ .retᴰ i
      elim-hom (α⁻⋆α i) = Bᴰ.αᴰ .nIsoᴰ _ .secᴰ i
      elim-hom η = Bᴰ.ηᴰ⟨ _ ⟩
      elim-hom (η-nat f i) = Bᴰ.ηᴰ .transᴰ .N-homᴰ (elim-hom f) i
      elim-hom η⁻ = Bᴰ.ηᴰ .nIsoᴰ _ .invᴰ
      elim-hom (η⋆η⁻ i) = Bᴰ.ηᴰ .nIsoᴰ _ .retᴰ i
      elim-hom (η⁻⋆η i) = Bᴰ.ηᴰ .nIsoᴰ _ .secᴰ i
      elim-hom ρ = Bᴰ.ρᴰ⟨ _ ⟩
      elim-hom (ρ-nat f i) = Bᴰ.ρᴰ .transᴰ .N-homᴰ (elim-hom f) i
      elim-hom ρ⁻ = Bᴰ.ρᴰ .nIsoᴰ _ .invᴰ
      elim-hom (ρ⋆ρ⁻ i) = Bᴰ.ρᴰ .nIsoᴰ _ .retᴰ i
      elim-hom (ρ⁻⋆ρ i) = Bᴰ.ρᴰ .nIsoᴰ _ .secᴰ i
      elim-hom (pentagon i) = Bᴰ.pentagonᴰ _ _ _ _ i
      elim-hom (triangle i) = Bᴰ.triangleᴰ _ _ i
      elim-hom lapp = Bᴰ.lresᴰ _ _ .elementᴰ
      elim-hom (llam f) =
        Bᴰ.lresᴰ _ _ .universalᴰ .isIsoOver.inv _ (elim-hom f)
      elim-hom (lβ f i) = Cᴰ.rectify {e' = lβ f}
        (Bᴰ.lresᴰ _ _ .universalᴰ .isIsoOver.rightInv _ (elim-hom f)) i
      elim-hom (lη g i) = Cᴰ.rectify {e' = lη g}
        (Bᴰ.lresᴰ _ _ .universalᴰ .isIsoOver.leftInv _ (elim-hom g)) i
      elim-hom rapp = Bᴰ.rresᴰ _ _ .elementᴰ
      elim-hom (rlam f) =
        Bᴰ.rresᴰ _ _ .universalᴰ .isIsoOver.inv _ (elim-hom f)
      elim-hom (rβ f i) = Cᴰ.rectify {e' = rβ f}
        (Bᴰ.rresᴰ _ _ .universalᴰ .isIsoOver.rightInv _ (elim-hom f)) i
      elim-hom (rη g i) = Cᴰ.rectify {e' = rη g}
        (Bᴰ.rresᴰ _ _ .universalᴰ .isIsoOver.leftInv _ (elim-hom g)) i

      elim : GlobalSection Bᴰ.Cᴰ
      elim .F-obᴰ = elim-ob
      elim .F-homᴰ = elim-hom
      elim .F-idᴰ = refl
      elim .F-seqᴰ _ _ = refl

  {- Universal property: restriction along ηFree from biclosed
     monoidal functors into N to functors into N.C has a section.  The
     residual structure is preserved on the nose, by refl. -}
  module _ (N : BiclosedMonoidalCategory ℓD ℓD') where
    private
      module N = BiclosedMonoidalCategory N
      module Nm = MonoidalCategory (BM→Mon N)
      Nᴰ = weakenBiclosed (FreeBiclosedOn C) N
    module _ (G : Functor C N.C) where
      rec : Functor (|FreeBiclosedOn| C) N.C
      rec = Wk.introS⁻ (elim Nᴰ (Wk.introS (ηFree C) G))

      rec-β : rec ∘F ηFree C ≡ G
      rec-β = Functor≡ (λ _ → refl) (λ _ → refl)

      -- rec strictly preserves the left residual: its vertex and its
      -- evaluation map are those of N.
      rec-lres-vertex : ∀ Δ Θ
        → rec ⟅ Δ ⊸ Θ ⟆ ≡ N.lres (rec ⟅ Δ ⟆) (rec ⟅ Θ ⟆) .vertex
      rec-lres-vertex Δ Θ = refl

      rec-lres-element : ∀ {Δ Θ}
        → rec ⟪ lapp {Δ = Δ} {Θ = Θ} ⟫
        ≡ N.lres (rec ⟅ Δ ⟆) (rec ⟅ Θ ⟆) .element
      rec-lres-element = refl

      rec-rres-vertex : ∀ Δ Θ
        → rec ⟅ Θ ⟜ Δ ⟆ ≡ N.rres (rec ⟅ Δ ⟆) (rec ⟅ Θ ⟆) .vertex
      rec-rres-vertex Δ Θ = refl

      rec-rres-element : ∀ {Δ Θ}
        → rec ⟪ rapp {Δ = Δ} {Θ = Θ} ⟫
        ≡ N.rres (rec ⟅ Δ ⟆) (rec ⟅ Θ ⟆) .element
      rec-rres-element = refl

      -- and strictly preserves the tensor and the unit, so it is
      -- strong monoidal with identity comparisons.
      rec-⊗ : ∀ x y → rec ⟅ x ⊗ y ⟆ ≡ (rec ⟅ x ⟆) N.⊗ (rec ⟅ y ⟆)
      rec-⊗ x y = refl

      rec-unit : rec ⟅ unit ⟆ ≡ N.unit
      rec-unit = refl

      recStr : StrongMonoidalFunctor (FreeMonoidal C) (BM→Mon N)
      recStr .F = rec
      recStr .strmonstr .laxmonstr .ε = Nm.id
      recStr .strmonstr .laxmonstr .μ .N-ob x = Nm.id
      recStr .strmonstr .laxmonstr .μ .N-hom f = Nm.⋆IdR _ ∙ sym (Nm.⋆IdL _)
      recStr .strmonstr .laxmonstr .αμ-law x y z =
        Nm.⋆IdR _
        ∙ cong₂ Nm._⋆_ refl (Nm.─⊗─ .F-id)
        ∙ Nm.⋆IdR _ ∙ sym (Nm.⋆IdL _)
        ∙ cong₂ Nm._⋆_ (sym (Nm.─⊗─ .F-id)) refl
        ∙ cong₂ Nm._⋆_ (sym (Nm.⋆IdR _)) refl
      recStr .strmonstr .laxmonstr .ηε-law x =
        cong₂ Nm._⋆_ (Nm.⋆IdR _ ∙ Nm.─⊗─ .F-id) refl ∙ Nm.⋆IdL _
      recStr .strmonstr .laxmonstr .ρε-law x =
        cong₂ Nm._⋆_ (Nm.⋆IdR _ ∙ Nm.─⊗─ .F-id) refl ∙ Nm.⋆IdL _
      recStr .strmonstr .ε-isIso = idCatIso .snd
      recStr .strmonstr .μ-isIso _ = idCatIso .snd

      -- The comparison maps are identities, so rec's image of `lapp`
      -- is N's evaluation map up to a unit law, and rec preserves the
      -- residuals in the sense TwoDim asks for.
      rec-⊸ : ∀ Δ Θ → isUniversal Nm.C
        (RPsh (A⊗-F (Nm.monstr .MonoidalStr.tenstr) (rec ⟅ Δ ⟆))
              (rec ⟅ Θ ⟆))
        (rec ⟅ Δ ⊸ Θ ⟆) (Nm.id Nm.⋆ rec ⟪ lapp ⟫)
      rec-⊸ Δ Θ = subst
        (isUniversal Nm.C _ (rec ⟅ Δ ⊸ Θ ⟆))
        (sym (Nm.⋆IdL _)) (N.lres _ _ .universal)

      rec-⟜ : ∀ Δ Θ → isUniversal Nm.C
        (RPsh (-⊗AF (Nm.monstr .MonoidalStr.tenstr) (rec ⟅ Δ ⟆))
              (rec ⟅ Θ ⟆))
        (rec ⟅ Θ ⟜ Δ ⟆) (Nm.id Nm.⋆ rec ⟪ rapp ⟫)
      rec-⟜ Δ Θ = subst
        (isUniversal Nm.C _ (rec ⟅ Θ ⟜ Δ ⟆))
        (sym (Nm.⋆IdL _)) (N.rres _ _ .universal)

  {- Two dimensional uniqueness.  A residual is contravariant in one
     of its arguments, so, exactly as for the exponential, there is no
     map `HΔ ⊸ HΘ → GΔ ⊸ GΘ` for a bare 2-cell to commute with at
     `Δ ⊸ Θ`.  What the induction needs there is a splitting of the
     component at `Δ`, so the hypothesis lands on the 2-cells; the
     tensor half meanwhile needs the transformations to be monoidal,
     just as in the free monoidal category. -}
  module TwoDim {M : MonoidalCategory ℓD ℓD'}
    (G H : StrongMonoidalFunctor (FreeMonoidal C) M)
    (H-⊸ : ∀ Δ Θ → isUniversal (M .MonoidalCategory.C)
      (RPsh (A⊗-F (M .MonoidalCategory.monstr .MonoidalStr.tenstr)
              (H .StrongMonoidalFunctor.F ⟅ Δ ⟆))
            (H .StrongMonoidalFunctor.F ⟅ Θ ⟆))
      (H .StrongMonoidalFunctor.F ⟅ Δ ⊸ Θ ⟆)
      (StrongMonoidalFunctor.μ⟨_,_⟩ H Δ (Δ ⊸ Θ)
        ⋆⟨ M .MonoidalCategory.C ⟩ (H .StrongMonoidalFunctor.F ⟪ lapp ⟫)))
    (H-⟜ : ∀ Δ Θ → isUniversal (M .MonoidalCategory.C)
      (RPsh (-⊗AF (M .MonoidalCategory.monstr .MonoidalStr.tenstr)
              (H .StrongMonoidalFunctor.F ⟅ Δ ⟆))
            (H .StrongMonoidalFunctor.F ⟅ Θ ⟆))
      (H .StrongMonoidalFunctor.F ⟅ Θ ⟜ Δ ⟆)
      (StrongMonoidalFunctor.μ⟨_,_⟩ H (Θ ⟜ Δ) Δ
        ⋆⟨ M .MonoidalCategory.C ⟩ (H .StrongMonoidalFunctor.F ⟪ rapp ⟫)))
    where
    private
      module M = MonoidalCategory M
      module G = StrongMonoidalFunctor G
      module H = StrongMonoidalFunctor H
      module HL (Δ Θ : BiOb C) =
        UniversalElementNotation (isUniversal→UniversalElement _ (H-⊸ Δ Θ))
      module HR (Δ Θ : BiOb C) =
        UniversalElementNotation (isUniversal→UniversalElement _ (H-⟜ Δ Θ))

    uniq₂ : (σ τ : NatTrans G.F H.F)
      → FM.isMonoidalNat G H σ → FM.isMonoidalNat G H τ
      → (s : ∀ A → M.C [ H.F ⟅ A ⟆ , G.F ⟅ A ⟆ ])
      → (∀ A → s A M.⋆ σ .N-ob A ≡ M.id)
      → (∀ c → σ .N-ob (↑ c) ≡ τ .N-ob (↑ c))
      → σ ≡ τ
    uniq₂ σ τ mσ mτ s sσ p↑ = makeNatTransPath (funExt go) where
      go : ∀ A → σ .N-ob A ≡ τ .N-ob A
      go (↑ c) = p↑ c
      go unit = ⋆CancelL G.ε-Iso (mσ .fst ∙ sym (mτ .fst))
      go (x ⊗ y) = ⋆CancelL (G.μ⟨ x , y ⟩ , G.μ-isIso (x , y))
        ( mσ .snd x y
        ∙ cong₂ M._⋆_ (cong₂ M._⊗ₕ_ (go x) (go y)) refl
        ∙ sym (mτ .snd x y))
      go (Δ ⊸ Θ) = HL.extensionality Δ Θ
        (lchain σ mσ (sσ Δ) ∙ cong (M._⋆_ m) (cong (M._⋆_ (G.F ⟪ lapp ⟫))
          (go Θ)) ∙ sym (lchain τ mτ sτΔ))
        where
        X = Δ ⊸ Θ
        sτΔ : s Δ M.⋆ τ .N-ob Δ ≡ M.id
        sτΔ = cong (M._⋆_ (s Δ)) (sym (go Δ)) ∙ sσ Δ
        m : M.C [ H.F ⟅ Δ ⟆ M.⊗ G.F ⟅ X ⟆ , G.F ⟅ Δ ⊗ X ⟆ ]
        m = (s Δ M.⊗ₕ M.id) M.⋆ G.μ⟨ Δ , X ⟩
        lchain : (ν : NatTrans G.F H.F) → FM.isMonoidalNat G H ν
          → s Δ M.⋆ ν .N-ob Δ ≡ M.id
          → (M.id M.⊗ₕ ν .N-ob X) M.⋆ (H.μ⟨ Δ , X ⟩ M.⋆ H.F ⟪ lapp ⟫)
          ≡ m M.⋆ (G.F ⟪ lapp ⟫ M.⋆ ν .N-ob Θ)
        lchain ν mν sν =
            M.⟨ cong₂ M._⊗ₕ_ (sym sν) (sym (M.⋆IdL _))
              ∙ M.─⊗─ .F-seq _ _ ⟩⋆⟨ refl ⟩
          ∙ M.⋆Assoc _ _ _
          ∙ M.⟨ refl ⟩⋆⟨ sym (M.⋆Assoc _ _ _)
                       ∙ M.⟨ sym (mν .snd Δ X) ⟩⋆⟨ refl ⟩
                       ∙ M.⋆Assoc _ _ _
                       ∙ M.⟨ refl ⟩⋆⟨ sym (ν .N-hom lapp) ⟩ ⟩
          ∙ sym (M.⋆Assoc _ _ _)
      go (Θ ⟜ Δ) = HR.extensionality Δ Θ
        (rchain σ mσ (sσ Δ) ∙ cong (M._⋆_ m) (cong (M._⋆_ (G.F ⟪ rapp ⟫))
          (go Θ)) ∙ sym (rchain τ mτ sτΔ))
        where
        X = Θ ⟜ Δ
        sτΔ : s Δ M.⋆ τ .N-ob Δ ≡ M.id
        sτΔ = cong (M._⋆_ (s Δ)) (sym (go Δ)) ∙ sσ Δ
        m : M.C [ G.F ⟅ X ⟆ M.⊗ H.F ⟅ Δ ⟆ , G.F ⟅ X ⊗ Δ ⟆ ]
        m = (M.id M.⊗ₕ s Δ) M.⋆ G.μ⟨ X , Δ ⟩
        rchain : (ν : NatTrans G.F H.F) → FM.isMonoidalNat G H ν
          → s Δ M.⋆ ν .N-ob Δ ≡ M.id
          → (ν .N-ob X M.⊗ₕ M.id) M.⋆ (H.μ⟨ X , Δ ⟩ M.⋆ H.F ⟪ rapp ⟫)
          ≡ m M.⋆ (G.F ⟪ rapp ⟫ M.⋆ ν .N-ob Θ)
        rchain ν mν sν =
            M.⟨ cong₂ M._⊗ₕ_ (sym (M.⋆IdL _)) (sym sν)
              ∙ M.─⊗─ .F-seq _ _ ⟩⋆⟨ refl ⟩
          ∙ M.⋆Assoc _ _ _
          ∙ M.⟨ refl ⟩⋆⟨ sym (M.⋆Assoc _ _ _)
                       ∙ M.⟨ sym (mν .snd X Δ) ⟩⋆⟨ refl ⟩
                       ∙ M.⋆Assoc _ _ _
                       ∙ M.⟨ refl ⟩⋆⟨ sym (ν .N-hom rapp) ⟩ ⟩
          ∙ sym (M.⋆Assoc _ _ _)

    -- The splitting is available whenever σ is a natural isomorphism.
    uniq₂Iso : (σ τ : NatTrans G.F H.F)
      → FM.isMonoidalNat G H σ → FM.isMonoidalNat G H τ
      → (σIso : ∀ A
          → Cubical.Categories.Category.Base.isIso M.C (σ .N-ob A))
      → (∀ c → σ .N-ob (↑ c) ≡ τ .N-ob (↑ c))
      → σ ≡ τ
    uniq₂Iso σ τ mσ mτ σIso = uniq₂ σ τ mσ mτ
      (λ A → σIso A .Cubical.Categories.Category.Base.isIso.inv)
      (λ A → σIso A .Cubical.Categories.Category.Base.isIso.sec)

  -- The hypotheses of TwoDim are met by the recursive extensions
  -- themselves, so uniq₂ is not vacuous.
  module recTwoDim {ℓ ℓ' : Level} (N : BiclosedMonoidalCategory ℓ ℓ')
    (G₁ G₂ : Functor C (N .BiclosedMonoidalCategory.C)) =
    TwoDim (recStr N G₁) (recStr N G₂) (rec-⊸ N G₂) (rec-⟜ N G₂)

{- The splitting hypothesis in `uniq₂` cannot be dropped, and there is
   no `rec₂`: a 2-cell between the restrictions need not extend at
   all.  `Δ ⊸ Θ` is contravariant in `Δ` and `Θ ⟜ Δ` is contravariant
   in `Δ`, so from components `σ Δ : G Δ → H Δ` there is no induced
   map `H Δ ⊸ H Θ → G Δ ⊸ G Θ`: transposing a candidate
   `G (Δ ⊸ Θ) → H (Δ ⊸ Θ)` asks for `H Δ ⊗ G (Δ ⊸ Θ) → H Θ`, and the
   only evaluation available is `G Δ ⊗ G (Δ ⊸ Θ) → G Θ`, so one needs
   `H Δ → G Δ`, the wrong direction.  This is the same obstruction
   that defeats `rec₂` for the free cartesian closed category, and the
   same counterexample applies: take D the walking arrow 0 -u-> 1 with
   its unique (cartesian, hence biclosed) monoidal structure, C the
   terminal category, F ↦ 0, G ↦ 1 and α = u.  An extension of ↑u
   would give, at ↑• ⊸ ↑•, a term h : ↑0 ⊸ ↑0 ⊢ M : ↑1 ⊸ ↑1; the
   context has no term of type ↑0, so the only βη-normal form is
   λ y. y, and naturality at `lapp` then demands ↑u (h x) ≡ ↑u x,
   which is false.  Hence |FreeBiclosedOn| is 2-functorial only on
   natural isomorphisms and there is no free biclosed monoidal
   2-monad on CAT. -}
