{- Free cartesian closed category generated by a category -}
{-# OPTIONS --lossy-unification #-}
module Cubical.Categories.Instances.Free.CartesianClosedCategory.OnCategory
  where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv
open import Cubical.Foundations.Function
open import Cubical.Foundations.Isomorphism
open import Cubical.Foundations.HLevels
open import Cubical.Data.Sigma hiding (_×_)
open import Cubical.Data.Unit

open import Cubical.Categories.Category.Base
open import Cubical.Categories.Functor
open import Cubical.Categories.NaturalTransformation hiding (_⇒_)
open import Cubical.Categories.Isomorphism
open import Cubical.Categories.Exponentials.Small
open import Cubical.Categories.Limits.Cartesian.Base
open import Cubical.Categories.Limits.CartesianClosed.Base
open import Cubical.Categories.Presheaf.Representable

open import Cubical.Categories.Displayed.Base
open import Cubical.Categories.Displayed.More
open import Cubical.Categories.Displayed.HLevels
open import Cubical.Categories.Displayed.Limits.CartesianV'
open import Cubical.Categories.Displayed.Limits.CartesianClosedV
open import Cubical.Categories.Displayed.Section.Base
open import Cubical.Categories.Displayed.Instances.Weaken.Base as Wk
open import Cubical.Categories.Displayed.Instances.Weaken.UncurriedProperties
open import Cubical.Categories.Limits.Terminal.More
open import Cubical.Categories.Limits.BinProduct.More
open import Cubical.Categories.Presheaf.Constructions.Reindex
open import Cubical.Categories.Presheaf.Constructions.Unit
open import Cubical.Categories.Presheaf.Morphism.Alt
open import Cubical.Categories.Presheaf.Representable.More
open import Cubical.Categories.Bicategory.Instances.CAT.Structured.Terminal
open import Cubical.Categories.Bicategory.Instances.CAT.Structured.Cartesian
open import
  Cubical.Categories.Bicategory.Instances.CAT.Structured.CartesianClosed
import Cubical.Data.Equality as Eq

private
  variable
    ℓC ℓC' ℓD ℓD' ℓE ℓE' ℓCᴰ ℓCᴰ' : Level

open Category
open Functor
open Section
open NatTrans
open UniversalElement
open CartesianCategory using (term; bp)
open CartesianClosedCategory using (CC; exps)

module _ (C : Category ℓC ℓC') where
  private module C = Category C

  data CCCOb : Type ℓC where
    ↑ : C .ob → CCCOb
    _×_ : CCCOb → CCCOb → CCCOb
    ⊤ : CCCOb
    _⇒_ : CCCOb → CCCOb → CCCOb

  data Exp : CCCOb → CCCOb → Type (ℓ-max ℓC ℓC') where
    idₑ : ∀ {Γ} → Exp Γ Γ
    _⋆ₑ_ : ∀ {Γ Γ' Γ''} → Exp Γ Γ' → Exp Γ' Γ'' → Exp Γ Γ''
    ⋆ₑIdL : ∀ {Γ Δ} (δ : Exp Γ Δ) → idₑ ⋆ₑ δ ≡ δ
    ⋆ₑIdR : ∀ {Γ Δ} (δ : Exp Γ Δ) → δ ⋆ₑ idₑ ≡ δ
    ⋆ₑAssoc : ∀ {Γ Γ' Γ'' Γ'''}
      (δ : Exp Γ Γ')(δ' : Exp Γ' Γ'')(δ'' : Exp Γ'' Γ''')
      → (δ ⋆ₑ δ') ⋆ₑ δ'' ≡ δ ⋆ₑ (δ' ⋆ₑ δ'')
    isSetExp : ∀ {Γ Γ'} → isSet (Exp Γ Γ')

    ↑ₘ : ∀ {x y} → C [ x , y ] → Exp (↑ x) (↑ y)
    ↑ₘId : ∀ {x} → ↑ₘ (C .id {x}) ≡ idₑ
    ↑ₘSeq : ∀ {x y z} (f : C [ x , y ])(g : C [ y , z ])
          → ↑ₘ (f ⋆⟨ C ⟩ g) ≡ ↑ₘ f ⋆ₑ ↑ₘ g

    !ₑ : ∀ {Γ} → Exp Γ ⊤
    ⊤η : ∀ {Γ} (t : Exp Γ ⊤) → t ≡ !ₑ
    π₁ : ∀ {Γ Δ} → Exp (Γ × Δ) Γ
    π₂ : ∀ {Γ Δ} → Exp (Γ × Δ) Δ
    ⟨_,_⟩ : ∀ {Γ Δ Δ'} → Exp Γ Δ → Exp Γ Δ' → Exp Γ (Δ × Δ')
    ×β₁ : ∀ {Γ Δ Δ'}{t : Exp Γ Δ}{t' : Exp Γ Δ'} → ⟨ t , t' ⟩ ⋆ₑ π₁ ≡ t
    ×β₂ : ∀ {Γ Δ Δ'}{t : Exp Γ Δ}{t' : Exp Γ Δ'} → ⟨ t , t' ⟩ ⋆ₑ π₂ ≡ t'
    ×η : ∀ {Γ Δ Δ'}{t : Exp Γ (Δ × Δ')} → t ≡ ⟨ t ⋆ₑ π₁ , t ⋆ₑ π₂ ⟩

    eval : ∀ {Δ Θ} → Exp ((Δ ⇒ Θ) × Δ) Θ
    λ-_ : ∀ {Γ Δ Θ} → Exp (Γ × Δ) Θ → Exp Γ (Δ ⇒ Θ)
    λβ : ∀ {Γ Δ Θ} (t : Exp (Γ × Δ) Θ)
       → ⟨ π₁ ⋆ₑ (λ- t) , π₂ ⟩ ⋆ₑ eval ≡ t
    λη : ∀ {Γ Δ Θ} (t : Exp Γ (Δ ⇒ Θ))
       → t ≡ (λ- (⟨ π₁ ⋆ₑ t , π₂ ⟩ ⋆ₑ eval))

  |FreeCCCOn| : Category ℓC (ℓ-max ℓC ℓC')
  |FreeCCCOn| .ob = CCCOb
  |FreeCCCOn| .Hom[_,_] = Exp
  |FreeCCCOn| .id = idₑ
  |FreeCCCOn| ._⋆_ = _⋆ₑ_
  |FreeCCCOn| .⋆IdL = ⋆ₑIdL
  |FreeCCCOn| .⋆IdR = ⋆ₑIdR
  |FreeCCCOn| .⋆Assoc = ⋆ₑAssoc
  |FreeCCCOn| .isSetHom = isSetExp

  FreeCCCOn : CartesianClosedCategory ℓC (ℓ-max ℓC ℓC')
  FreeCCCOn .CC .CartesianCategory.C = |FreeCCCOn|
  FreeCCCOn .CC .term .vertex = ⊤
  FreeCCCOn .CC .term .element = tt
  FreeCCCOn .CC .term .universal _ =
    isIsoToIsEquiv ((λ _ → !ₑ) , ((λ _ → refl) , λ _ → sym $ ⊤η _))
  FreeCCCOn .CC .bp (Γ , Δ) .vertex = Γ × Δ
  FreeCCCOn .CC .bp (Γ , Δ) .element = π₁ , π₂
  FreeCCCOn .CC .bp (Γ , Δ) .universal Θ = isIsoToIsEquiv
    ( (λ z → ⟨ z .fst , z .snd ⟩)
    , (λ _ → ΣPathP (×β₁ , ×β₂))
    , (λ _ → sym $ ×η))
  FreeCCCOn .exps Δ Θ .vertex = Δ ⇒ Θ
  FreeCCCOn .exps Δ Θ .element = eval
  FreeCCCOn .exps Δ Θ .universal Γ =
    isIsoToIsEquiv (λ-_ , λβ , λ t → sym (λη t))

  FreeCartesianOn : CartesianCategory ℓC (ℓ-max ℓC ℓC')
  FreeCartesianOn = FreeCCCOn .CC

  ηFree : Functor C |FreeCCCOn|
  ηFree .F-ob = ↑
  ηFree .F-hom = ↑ₘ
  ηFree .F-id = ↑ₘId
  ηFree .F-seq = ↑ₘSeq

  -- Elimination: a section along ηFree of a displayed cartesian
  -- closed category extends to a global section.
  module _ (CCCᴰ : CartesianClosedCategoryᴰ FreeCCCOn ℓCᴰ ℓCᴰ') where
    open CartesianClosedCategoryᴰ CCCᴰ
    module _ (ı : Section ηFree Cᴰ) where
      private module ı = Section ı

      elim-ob : ∀ A → Cᴰ.ob[ A ]
      elim-ob (↑ x) = ı.F-obᴰ x
      elim-ob (A × B) = bpᴰ (elim-ob A) (elim-ob B) .fst
      elim-ob ⊤ = termᴰ .fst
      elim-ob (A ⇒ B) = expᴰ (elim-ob A) (elim-ob B) .fst

      elim-hom : ∀ {A B} (f : |FreeCCCOn| [ A , B ])
        → Cᴰ [ f ][ elim-ob A , elim-ob B ]
      elim-hom idₑ = Cᴰ.idᴰ
      elim-hom (f ⋆ₑ g) = elim-hom f Cᴰ.⋆ᴰ elim-hom g
      elim-hom (⋆ₑIdL f i) = Cᴰ.⋆IdLᴰ (elim-hom f) i
      elim-hom (⋆ₑIdR f i) = Cᴰ.⋆IdRᴰ (elim-hom f) i
      elim-hom (⋆ₑAssoc f g h i) =
        Cᴰ.⋆Assocᴰ (elim-hom f) (elim-hom g) (elim-hom h) i
      elim-hom (isSetExp f g p q i j) =
        isSetHomᴰ' Cᴰ (elim-hom f) (elim-hom g)
          (cong elim-hom p) (cong elim-hom q) i j
      elim-hom (↑ₘ f) = ı.F-homᴰ f
      elim-hom (↑ₘId i) = ı.F-idᴰ i
      elim-hom (↑ₘSeq f g i) = ı.F-seqᴰ f g i
      elim-hom !ₑ = termᴰ.introᴰ tt
      elim-hom (⊤η f i) = Cᴰ.rectify {e' = ⊤η f} (termᴰ.ηᴰ (elim-hom f)) i
      elim-hom π₁ = bpᴰ.πᴰ₁
      elim-hom π₂ = bpᴰ.πᴰ₂
      elim-hom ⟨ f , g ⟩ = bpᴰ.introᴰ (elim-hom f , elim-hom g)
      elim-hom (×β₁ {t = f}{t' = g} i) =
        Cᴰ.rectify {e' = ×β₁} (bpᴰ.×βᴰ₁ (elim-hom f) (elim-hom g)) i
      elim-hom (×β₂ {t = f}{t' = g} i) =
        Cᴰ.rectify {e' = ×β₂} (bpᴰ.×βᴰ₂ (elim-hom f) (elim-hom g)) i
      elim-hom (×η {t = f} i) =
        Cᴰ.rectify {e' = ×η} (bpᴰ.×ηᴰ (elim-hom f)) i
      elim-hom eval = appᴰ
      elim-hom (λ- f) = λᴰ (elim-hom f)
      elim-hom (λβ f i) =
        Cᴰ.rectify {e' = λβ f} (Cᴰ.≡out $ ⇒βᴰ (elim-hom f)) i
      elim-hom (λη f i) =
        Cᴰ.rectify {e' = λη f} (Cᴰ.≡out $ ⇒ηᴰ (elim-hom f)) i

      elim : GlobalSection Cᴰ
      elim .F-obᴰ = elim-ob
      elim .F-homᴰ = elim-hom
      elim .F-idᴰ = refl
      elim .F-seqᴰ _ _ = refl

  -- Universal property: restriction along ηFree from CCC-preserving
  -- functors into CCC to functors into CCC.C has a section.
  module _ (CCC : CartesianClosedCategory ℓD ℓD') where
    private
      module CCC = CartesianClosedCategory CCC
      wkCCC = weakenCCC FreeCCCOn CCC
    module _ (G : Functor C CCC.C) where
      rec : Functor |FreeCCCOn| CCC.C
      rec = Wk.introS⁻ (elim wkCCC (Wk.introS ηFree G))

      rec-β : rec ∘F ηFree ≡ G
      rec-β = Functor≡ (λ _ → refl) (λ _ → refl)

      rec-preservesBinProducts :
        preservesProvidedBinProducts rec (FreeCartesianOn .bp)
      rec-preservesBinProducts A B =
        strictlyPreservesUniversalElement (preservesBinProdCones rec A B)
          (FreeCartesianOn .bp (A , B)) (CCC.bp _) Eq.refl refl

      rec-preservesTerminal : preservesTerminal' rec (FreeCartesianOn .term)
      rec-preservesTerminal =
        strictlyPreservesUniversalElement
          (invPshIso (reindPsh-Unit rec) .PshIso.trans)
          (FreeCartesianOn .term) CCC.term Eq.refl refl

  {- Preservation of the exponentials, at the levels at which the
     exponential comparison heteromorphism is defined. -}
  module _ (CCC : CartesianClosedCategory ℓC (ℓ-max ℓC ℓC'))
           (G : Functor C (CartesianClosedCategory.C CCC)) where
    private
      module CCC = CartesianClosedCategory CCC
      module D = Category CCC.C
      R = rec CCC G
      Rbp = rec-preservesBinProducts CCC G

    rec-preservesExponentials :
      preservesExponentials R CCC.bp (FreeCCCOn .exps) Rbp
    rec-preservesExponentials c d =
      veryStrictlyPreservesUniversalElement
        (⇒PshSmallHet R (FreeCartesianOn .bp) CCC.bp Rbp c d)
        (FreeCCCOn .exps c d)
        (CCC.exps _ _ .element)
        (CCC.exps _ _ .universal)
        (sym (D.⋆IdL _) ∙ D.⟨ sym comp≡id ⟩⋆⟨ refl ⟩)
      where
      module PC = ProdComparison R (FreeCartesianOn .bp) CCC.bp Rbp c
      comp≡id : PC.comp⁻¹ (c ⇒ d) ≡ D.id
      comp≡id = PC.img.extensionality (c ⇒ d) (ΣPathP
        ( PC.comp⁻¹β₁ (c ⇒ d) ∙ sym (D.⋆IdL _)
        , PC.comp⁻¹β₂ (c ⇒ d) ∙ sym (D.⋆IdL _)))

  {- Two dimensional uniqueness.  Unlike the cartesian case, the
     exponential comparison cannot be commuted with a bare 2-cell: it
     is contravariant in its first argument, so there is no map
     `QA ⇒ QB → PA ⇒ PB` to compare against.  What the induction needs
     at `A ⇒ B` is a splitting of the component at `A`, which is why
     the hypothesis lands on the 2-cells and not on `Q`. -}
  module TwoDim {D : Category ℓC (ℓ-max ℓC ℓC')} (bpD : BinProducts D)
    (P Q : Functor |FreeCCCOn| D)
    (P-× : preservesProvidedBinProducts P (FreeCartesianOn .bp))
    (Q-1 : preservesTerminal' Q (FreeCartesianOn .term))
    (Q-× : preservesProvidedBinProducts Q (FreeCartesianOn .bp))
    (Q-⇒ : preservesExponentials Q bpD (FreeCCCOn .exps) Q-×)
    where
    private
      module D = Category D
      module Q⊤ = UniversalElementNotation
        (isUniversal→UniversalElement UnitPsh Q-1)
      module Q× {A B} = UniversalElementNotation
        (isUniversal→UniversalElement _ (Q-× A B))

    uniq₂ : (σ τ : NatTrans P Q)
      → (s : ∀ A → D [ Q ⟅ A ⟆ , P ⟅ A ⟆ ])
      → (∀ A → s A D.⋆ σ .N-ob A ≡ D.id)
      → (∀ c → σ .N-ob (↑ c) ≡ τ .N-ob (↑ c))
      → σ ≡ τ
    uniq₂ σ τ s sσ p↑ = makeNatTransPath (funExt go) where
      go : ∀ A → σ .N-ob A ≡ τ .N-ob A
      go (↑ c) = p↑ c
      go ⊤ = Q⊤.extensionality refl
      go (A × B) = Q×.extensionality (ΣPathP
        ( sym (σ .N-hom π₁) ∙ cong (D._⋆_ (P ⟪ π₁ ⟫)) (go A)
          ∙ τ .N-hom π₁
        , sym (σ .N-hom π₂) ∙ cong (D._⋆_ (P ⟪ π₂ ⟫)) (go B)
          ∙ τ .N-hom π₂))
      go (A ⇒ B) = Qexp.extensionality (cancel
        ( chain σ refl
        ∙ cong (D._⋆_ (P ⟪ eval {Δ = A} {Θ = B} ⟫)) (go B)
        ∙ sym (chain τ (sym (go A)))))
        where
        X = A ⇒ B
        module PC = ProdComparison P (FreeCartesianOn .bp) bpD P-× A
        module QC = ProdComparison Q (FreeCartesianOn .bp) bpD Q-× A
        module bPQ = BinProductNotation (bpD (P ⟅ X ⟆ , Q ⟅ A ⟆))
        module bQQ = BinProductNotation (bpD (Q ⟅ X ⟆ , Q ⟅ A ⟆))
        module Qexp = UniversalElementNotation
          (becomesUniversal→UniversalElement
            (⇒PshSmallHet Q (FreeCartesianOn .bp) bpD Q-× A B) (Q-⇒ A B))

        -- the mediating map P (X × A) → P X ×_D Q A, a split mono
        m : D [ P ⟅ X × A ⟆ , bPQ.vert ]
        m = P ⟪ π₁ ⟫ bPQ.,p (P ⟪ π₂ ⟫ D.⋆ σ .N-ob A)

        n : D [ bPQ.vert , P ⟅ X × A ⟆ ]
        n = PC.img.intro X (bPQ.π₁ , (bPQ.π₂ D.⋆ s A))

        nm : n D.⋆ m ≡ D.id
        nm = bPQ.,p-extensionality
          ( D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ bPQ.×β₁ ⟩
            ∙ cong fst (PC.img.β X) ∙ sym (D.⋆IdL _))
          ( D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ bPQ.×β₂ ⟩
            ∙ sym (D.⋆Assoc _ _ _)
            ∙ D.⟨ cong snd (PC.img.β X) ⟩⋆⟨ refl ⟩
            ∙ D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ sσ A ⟩ ∙ D.⋆IdR _
            ∙ sym (D.⋆IdL _))

        cancel : ∀ {f g : D [ bPQ.vert , Q ⟅ B ⟆ ]}
          → m D.⋆ f ≡ m D.⋆ g → f ≡ g
        cancel q =
            sym (D.⋆IdL _) ∙ D.⟨ sym nm ⟩⋆⟨ refl ⟩ ∙ D.⋆Assoc _ _ _
          ∙ cong (D._⋆_ n) q
          ∙ sym (D.⋆Assoc _ _ _) ∙ D.⟨ nm ⟩⋆⟨ refl ⟩ ∙ D.⋆IdL _

        -- the comparison Q (X × A) → Q X ×_D Q A inverts QC.comp⁻¹
        cQ : D [ Q ⟅ X × A ⟆ , bQQ.vert ]
        cQ = Q ⟪ π₁ ⟫ bQQ.,p Q ⟪ π₂ ⟫

        cQcomp : cQ D.⋆ QC.comp⁻¹ X ≡ D.id
        cQcomp = QC.img.extensionality X (ΣPathP
          ( D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ QC.comp⁻¹β₁ X ⟩ ∙ bQQ.×β₁
            ∙ sym (D.⋆IdL _)
          , D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ QC.comp⁻¹β₂ X ⟩ ∙ bQQ.×β₂
            ∙ sym (D.⋆IdL _)))

        chain : (ρ : NatTrans P Q) → ρ .N-ob A ≡ σ .N-ob A
          → m D.⋆ (QC.×FcF ⟪ ρ .N-ob X ⟫ D.⋆ Qexp.element)
            ≡ P ⟪ eval {Δ = A} {Θ = B} ⟫ D.⋆ ρ .N-ob B
        chain ρ ρA =
            sym (D.⋆Assoc _ _ _)
          ∙ D.⟨ mρ ⟩⋆⟨ refl ⟩
          ∙ D.⋆Assoc _ _ _
          ∙ D.⟨ refl ⟩⋆⟨ sym (D.⋆Assoc _ _ _) ∙ D.⟨ cQcomp ⟩⋆⟨ refl ⟩
                         ∙ D.⋆IdL _ ⟩
          ∙ sym (ρ .N-hom (eval {Δ = A} {Θ = B}))
          where
          mρ : m D.⋆ QC.×FcF ⟪ ρ .N-ob X ⟫ ≡ ρ .N-ob (X × A) D.⋆ cQ
          mρ = bQQ.,p-extensionality
            ( D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ QC.×FcFβ₁ (ρ .N-ob X) ⟩
              ∙ sym (D.⋆Assoc _ _ _) ∙ D.⟨ bPQ.×β₁ ⟩⋆⟨ refl ⟩
              ∙ ρ .N-hom (π₁ {Γ = X} {Δ = A})
              ∙ sym (D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ bQQ.×β₁ ⟩) )
            ( D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ QC.×FcFβ₂ (ρ .N-ob X) ⟩
              ∙ bPQ.×β₂ ∙ D.⟨ refl ⟩⋆⟨ sym ρA ⟩
              ∙ ρ .N-hom (π₂ {Γ = X} {Δ = A})
              ∙ sym (D.⋆Assoc _ _ _ ∙ D.⟨ refl ⟩⋆⟨ bQQ.×β₂ ⟩) )

    -- The hypothesis is satisfied whenever σ is a natural isomorphism.
    uniq₂Iso : (σ τ : NatTrans P Q)
      → (σIso : ∀ A → Cubical.Categories.Category.Base.isIso D (σ .N-ob A))
      → (∀ c → σ .N-ob (↑ c) ≡ τ .N-ob (↑ c))
      → σ ≡ τ
    uniq₂Iso σ τ σIso = uniq₂ σ τ
      (λ A → σIso A .Cubical.Categories.Category.Base.isIso.inv)
      (λ A → σIso A .Cubical.Categories.Category.Base.isIso.sec)

  {- The splitting hypothesis cannot be dropped, and there is no
     `rec₂`: a 2-cell need not extend at all.  Take D the walking arrow
     0 -u-> 1, C the terminal category, F ↦ 0, G ↦ 1 and α = u.  An
     extension σ of ↑u would give, at ↑• ⇒ ↑•, a term
     h : ↑0 ⇒ ↑0 ⊢ M : ↑1 ⇒ ↑1; the context has no term of type ↑0, so
     the only normal form is λ y. y.  Naturality at eval then demands
     ↑u (h x) ≡ ↑u x, which is false.  Hence |FreeCCCOn| is 2-functorial
     only on natural isomorphisms and there is no free cartesian closed
     2-monad on CAT. -}
